const Talents = [
  {
    nameEn: 'Freedom',
    nameVi: 'Tự Do',
    dayEn: 'Monday, Thursday',
    dayVi: 'Thứ hai, Thứ năm',
    characters: [
      { name: 'Amber', element: 'Pyro' },
      { name: 'Barbara', element: 'Hydro' },
      { name: 'Diona', element: 'Cryo' },
      { name: 'Klee', element: 'Pyro' },
      { name: 'Sucrose', element: 'Anemo' },
      { name: 'Tartaglia', element: 'Hydro' },
      { name: 'Traveler (Anemo)', element: 'Anemo' },
      { name: 'Traveler (Geo)', element: 'Geo' },
    ],
  },
  {
    nameEn: 'Prosperity',
    nameVi: 'Phồn Vinh',
    dayEn: 'Monday, Thursday',
    dayVi: 'Thứ hai, Thứ năm',
    characters: [
      { name: 'Keqing', element: 'Electro' },
      { name: 'Ningguang', element: 'Geo' },
      { name: 'Qiqi', element: 'Cryo' },
      { name: 'Xiao', element: 'Anemo' },
    ],
  },
  {
    nameEn: 'Resistance',
    nameVi: 'Kháng Chiến',
    dayEn: 'Tuesday, Friday',
    dayVi: 'Thứ ba, Thứ sáu',
    characters: [
      { name: 'Bennett', element: 'Pyro' },
      { name: 'Diluc', element: 'Pyro' },
      { name: 'Jean', element: 'Anemo' },
      { name: 'Mona', element: 'Hydro' },
      { name: 'Noelle', element: 'Geo' },
      { name: 'Razor', element: 'Electro' },
      { name: 'Traveler (Anemo)', element: 'Anemo' },
      { name: 'Traveler (Geo)', element: 'Geo' },
    ],
  },
  {
    nameEn: 'Diligence',
    nameVi: 'Chăm Chỉ',
    dayEn: 'Tuesday, Friday',
    dayVi: 'Thứ ba, Thứ sáu',
    characters: [
      { name: 'Chongyun', element: 'Cryo' },
      { name: 'Ganyu', element: 'Cryo' },
      { name: 'Xiangling', element: 'Pyro' },
    ],
  },
  {
    nameEn: 'Ballad',
    nameVi: 'Thơ Ca',
    dayEn: 'Wednesday, Saturday',
    dayVi: 'Thứ tư, Thứ bảy',
    characters: [
      { name: 'Albedo', element: 'Geo' },
      { name: 'Fischl', element: 'Electro' },
      { name: 'Kaeya', element: 'Cryo' },
      { name: 'Lisa', element: 'Electro' },
      { name: 'Traveler (Anemo)', element: 'Anemo' },
      { name: 'Traveler (Geo)', element: 'Geo' },
      { name: 'Venti', element: 'Anemo' },
    ],
  },
  {
    nameEn: 'Gold',
    nameVi: 'Hoàng Kim',
    dayEn: 'Wednesday, Saturday',
    dayVi: 'Thứ tư, Thứ bảy',
    characters: [
      { name: 'Beidou', element: 'Electro' },
      { name: 'Xingqiu', element: 'Hydro' },
      { name: 'Xinyan', element: 'Pyro' },
      { name: 'Zhongli', element: 'Geo' },
    ],
  },
  {
    nameEn: 'Tail of Boreas',
    nameVi: 'Lông Vũ Bắc Phong',
    dayEn: 'Andrius',
    dayVi: 'Sói Bắc Phong',
    characters: [
      { name: 'Qiqi', element: 'Cryo' },
      { name: 'Venti', element: 'Anemo' },
      { name: 'Xingqiu', element: 'Hydro' },
    ],
  },
  {
    nameEn: 'Ring of Boreas',
    nameVi: 'Móng Vuốt Bắc Phong',
    dayEn: 'Andrius',
    dayVi: 'Sói Bắc Phong',
    characters: [
      { name: 'Barbara', element: 'Hydro' },
      { name: 'Keqing', element: 'Electro' },
      { name: 'Klee', element: 'Pyro' },
      { name: 'Mona', element: 'Hydro' },
    ],
  },
  {
    nameEn: 'Spirit Locket of Boreas',
    nameVi: 'Linh Hồn Bắc Phong',
    dayEn: 'Andrius',
    dayVi: 'Sói Bắc Phong',
    characters: [
      { name: 'Fischl', element: 'Electro' },
      { name: 'Kaeya', element: 'Cryo' },
      { name: 'Ningguang', element: 'Geo' },
      { name: 'Sucrose', element: 'Anemo' },
    ],
  },
  {
    nameEn: "Dvalin's Plume",
    nameVi: 'Lông Vũ Đông Phong',
    dayEn: 'Dvalin',
    dayVi: 'Phong Ma Long',
    characters: [
      { name: 'Bennett', element: 'Pyro' },
      { name: 'Diluc', element: 'Pyro' },
      { name: 'Jean', element: 'Anemo' },
    ],
  },
  {
    nameEn: "Dvalin's Claw",
    nameVi: 'Móng Vuốt Đông Phong',
    dayEn: 'Dvalin',
    dayVi: 'Phong Ma Long',
    characters: [
      { name: 'Lisa', element: 'Electro' },
      { name: 'Noelle', element: 'Geo' },
      { name: 'Razor', element: 'Electro' },
      { name: 'Xiangling', element: 'Pyro' },
    ],
  },
  {
    nameEn: "Dvalin's Sigh",
    nameVi: 'Hơi Thở Đông Phong',
    dayEn: 'Dvalin',
    dayVi: 'Phong Ma Long',
    characters: [
      { name: 'Amber', element: 'Pyro' },
      { name: 'Beidou', element: 'Electro' },
      { name: 'Chongyun', element: 'Cryo' },
      { name: 'Traveler (Anemo)', element: 'Anemo' },
      { name: 'Traveler (Geo)', element: 'Geo' },
    ],
  },
  {
    nameEn: 'Tusk of Monoceros Caeli',
    nameVi: 'Tôn Thiên Kình-Sừng',
    dayEn: 'Tartaglia',
    dayVi: 'Tartaglia',
    characters: [
      { name: 'Albedo', element: 'Geo' },
      { name: 'Xinyan', element: 'Pyro' },
      { name: 'Zhongli', element: 'Geo' },
    ],
  },
  {
    nameEn: 'Shard of a Foul Legacy',
    nameVi: 'Đao Ma Vương-Mảnh Vỡ',
    dayEn: 'Tartaglia',
    dayVi: 'Tartaglia',
    characters: [
      { name: 'Diona', element: 'Cryo' },
      { name: 'Tartaglia', element: 'Hydro' },
    ],
  },
  {
    nameEn: 'Shadow of the Warrior',
    nameVi: 'Linh Hồn Võ Luyện-Cô Độc',
    dayEn: 'Tartaglia',
    dayVi: 'Tartaglia',
    characters: [{ name: 'Ganyu', element: 'Cryo' }],
  },
]

export { Talents }
