const BaseWeapon = [
  { en: 'Bow', vi: 'Cung' },
  { en: 'Catalyst', vi: 'Pháp khí' },
  { en: 'Claymore', vi: 'Trọng kiếm' },
  { en: 'Polearm', vi: 'Thương' },
  { en: 'Sword', vi: 'Kiếm đơn' },
]

const typeEn = {
  Bow: BaseWeapon[0].en,
  Catalyst: BaseWeapon[1].en,
  Claymore: BaseWeapon[2].en,
  Polearm: BaseWeapon[3].en,
  Sword: BaseWeapon[4].en,
}

const typeVi = {
  Bow: BaseWeapon[0].vi,
  Catalyst: BaseWeapon[1].vi,
  Claymore: BaseWeapon[2].vi,
  Polearm: BaseWeapon[3].vi,
  Sword: BaseWeapon[4].vi,
}

const secondEn = {
  ATK: 'ATK',
  DEF: 'DEF',
  HP: 'HP',
  ER: 'Energy Recharge',
  EM: 'Elemental Mastery',
  CR: 'CRIT Rate',
  CD: 'CRIT DMG',
  PDM: 'Physical DMG Bonus',
}
const secondVi = {
  ATK: 'ATK',
  DEF: 'DEF',
  HP: 'HP',
  ER: 'Hiệu Quả Nạp Nguyên Tố',
  EM: 'Tinh Thông Nguyên Tố',
  CR: 'Tỉ Lệ Bạo Kích',
  CD: 'Sát Thương Bạo Kích',
  PDM: 'Tăng Sát Thương Vật Lý',
}

const WeaponList2 = [
  {
    nameEn: 'Summit Shaper',
    nameVi: 'Kiếm Chước Phong',
    typeEn: typeEn.Sword,
    typeVi: typeVi.Sword,
    rarity: 5,
    ATK: 46,
    secondaryVi: secondEn.ATK,
    secondaryEn: secondVi.ATK,
    bonusEn:
      'Increases Shield Strength by <b>20/25/30/35/40%</b>. Scoring hits on opponents increases ATK by <b>4/5/6/7/8%</b> for 8s. Max 5 stacks. Can only occur once every 0.3s. While protected by a shield, this ATK increase effect is increased by 100%.',
    bonusVi:
      'Hiệu quả giáp tăng <b>20/25/30/35/40%</b>, Trong vòng 8 giây sau khi đánh trúng, tấn công tăng <b>4/5/6/7/8%</b>. Cộng dồn 5 tầng, mỗi 0.3 giây chỉ được thi triển 1 lần. Ngoài ra khi được khiên bảo vệ, hiệu quả tấn công tăng 100%.',
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: 'Skyward Blade',
    nameVi: 'Thiên Không Kiếm',
    typeEn: typeEn.Sword,
    typeVi: typeVi.Sword,
    rarity: 5,
    ATK: 46,
    secondaryVi: 'Hiệu quả nạp nguyên tố',
    secondaryEn: 'Energy Recharge',
    bonusEn:
      'CRIT Rate increased by <b>4/5/6/7/8%</b>. Gains Skypiercing Might upon using an Elemental Burst:<br>Increases Movement SPD by 10%, increases ATK SPD by 10%, and increases the DMG of Normal and Charged Attack hits by <b>20/25/30/35/40%</b> for 12s.',
    bonusVi:
      'Tỷ lệ bạo kích tăng <b>4/5/6/7/8%</b>, khi thi triển kỹ năng nộ nhận khí thế phá hủy trên không:<br>Tốc độ di chuyển tăng 10%, tốc độ tấn công tăng 10%, và sát thương tấn công thường hoặc trọng kích tăng <b>20/25/30/35/40%</b>, kéo dài 12s.',
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
]

const WeaponList = [
  {
    nameEn: 'Summit Shaper',
    nameVi: 'Kiếm Chước Phong',
    typeEn: typeEn.Sword,
    typeVi: typeVi.Sword,
    rarity: 5,
    ATK: 46,
    secondaryVi: secondVi.ATK,
    secondaryEn: secondEn.ATK,
    bonusEn:
      'Increases Shield Strength by <b>20/25/30/35/40%</b>. Scoring hits on opponents increases ATK by <b>4/5/6/7/8%</b> for 8s. Max 5 stacks. Can only occur once every 0.3s. While protected by a shield, this ATK increase effect is increased by 100%.',
    bonusVi:
      'Hiệu quả giáp tăng <b>20/25/30/35/40%</b>, Trong vòng 8 giây sau khi đánh trúng, tấn công tăng <b>4/5/6/7/8%</b>. Cộng dồn 5 tầng, mỗi 0.3 giây chỉ được thi triển 1 lần. Ngoài ra khi được khiên bảo vệ, hiệu quả tấn công tăng 100%.',
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: 'Skyward Blade',
    nameVi: 'Thiên Không Kiếm',
    typeEn: typeEn.Sword,
    typeVi: typeVi.Sword,
    rarity: 5,
    ATK: 46,
    secondaryVi: secondVi.ER,
    secondaryEn: secondEn.ER,
    bonusEn:
      'CRIT Rate increased by <b>4/5/6/7/8%</b>. Gains Skypiercing Might upon using an Elemental Burst:<br>Increases Movement SPD by 10%, increases ATK SPD by 10%, and increases the DMG of Normal and Charged Attack hits by <b>20/25/30/35/40%</b> for 12s.',
    bonusVi:
      'Tỷ lệ bạo kích tăng <b>4/5/6/7/8%</b>, khi thi triển kỹ năng nộ nhận khí thế phá hủy trên không:<br>Tốc độ di chuyển tăng 10%, tốc độ tấn công tăng 10%, và sát thương tấn công thường hoặc trọng kích tăng <b>20/25/30/35/40%</b>, kéo dài 12s.',
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: 'Primordial Jade Cutter',
    nameVi: 'Bàn Nham Kết Lục',
    typeEn: typeEn.Sword,
    typeVi: typeVi.Sword,
    rarity: 5,
    ATK: 44,
    secondaryVi: secondVi.CR,
    secondaryEn: secondEn.CR,
    bonusVi:
      'HP tăng <b>20/25/30/35/40%</b>. Ngoài ra, nhận được buff tấn công dựa trên <b>1.2/1.5/1.8/2.1/2.4%</b> giới hạn HP của nhân vật trang bị vũ khí này.	',
    bonusEn:
      "HP increased by <b>20/25/30/35/40%</b>. Additionally, provides an ATK bonus based on <b>1.2/1.5/1.8/2.1/2.4%</b> of the weilder's Max HP.",
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: 'Aquila Favonia',
    nameVi: 'Phong Ưng Kiếm',
    typeEn: typeEn.Sword,
    typeVi: typeVi.Sword,
    rarity: 5,
    ATK: 48,
    secondaryVi: secondVi.PDM,
    secondaryEn: secondEn.PDM,
    bonusVi:
      'Tấn công tăng <b>20/25/30/35/40%</b>. Kích hoạt khi chịu sát thương: Linh hồn Tây Phong Ưng thức tỉnh dưới cờ hiệu kháng chiến, hồi HP bằng <b>100/115/130/145/160%</b> tấn công và gây cho địch xung quanh sát thương bằng <b>200/230/260/290/320%</b> lực tấn công. Mỗi 15s kích hoạt 1 lần.	',
    bonusEn:
      'ATK is increased by <b>20/25/30/35/40%</b>. Triggers on taking DMG: the soul of the Falcon of the West awakens, holding the banner of the resistance aloft, regenerating HP equal to <b>100/115/130/145/160%</b> of ATK and dealing <b>200/230/260/290/320%</b> of ATK as DMG to surrounding enemies. This effect can only occur once every 15s.',
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: 'Vortex Vanquisher',
    nameVi: 'Giáo Nịnh Thần',
    typeEn: typeEn.Polearm,
    typeVi: typeVi.Polearm,
    rarity: 5,
    ATK: 46,
    secondaryVi: secondVi.ATK,
    secondaryEn: secondEn.ATK,
    bonusVi:
      'Hiệu quả khiên tăng <b>20/25/30/35/40%</b>. Trong vòng 8s sau khi đánh trúng, tấn công tăng <b>4/5/6/7/8%</b>. Cộng dồn 5 tầng, mỗi 0.3s chỉ được thi triển 1 lần. Ngoài ra, khi được khiên bảo vệ, hiệu quả tăng tấn công sẽ tăng 100%.	',
    bonusEn:
      'Increases Shield Strength by <b>20/25/30/35/40%</b>, scoring hits on opponents increases ATK by <b>4/5/6/7/8%</b> for 8s. Max 5 stacks. Can only occur once every 0.3s. While protected by a shield this ATK increase effect is increased by 100%',
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: 'Staff of Homa',
    nameVi: 'Trượng Hộ Ma',
    typeEn: typeEn.Polearm,
    typeVi: typeVi.Polearm,
    rarity: 5,
    ATK: 46,
    secondaryVi: secondVi.CD,
    secondaryEn: secondEn.CD,
    bonusVi:
      'HP tăng <b>20/25/30/35/40%</b>. Ngoài ra, nhận được buff tấn công bằng <b>0.8/1/1.2/1.4/1.6%</b> giới hạn HP của nhân vật trang bị vũ khí này. Khi HP của nhân vật trang bị vũ khí này dưới 50%, sẽ nhận thêm buff tấn công bằng <b>1/1.2/1.4/1.6/1.8%</b> giới hạn HP.	',
    bonusEn:
      "HP increased by <b>20/25/30/35/40%</b>. Additionally, provides an ATK Bonus based on <b>0.8/1/1.2/1.4/1.6%</b> of the wielder's Max HP. When the wielder's HP is less than 50%, this ATK bonus is increased by an additional <b>1/1.2/1.4/1.6/1.8%</b> of Max HP.",
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: 'Skyward Spine',
    nameVi: 'Xương Sống Thiên Không',
    typeEn: typeEn.Polearm,
    typeVi: typeVi.Polearm,
    rarity: 5,
    ATK: 48,
    secondaryVi: secondVi.ER,
    secondaryEn: secondEn.ER,
    bonusVi:
      'Tỷ lệ bạo kích tăng <b>8/10/12/14/16%</b>,tốc độ tấn công thường tăng 12%. Ngoài ra, khi tấn công thường và trọng kích đánh trúng kẻ địch, có tỷ lệ 50% thi triển Lưỡi Dao Chân Không, tạo thêm sát thương bằng <b>40/55/70/85/100%</b> tấn công trong phạm vi nhỏ. Hiệu quả này mỗi 2s thi triển nhiều nhất 1 lần.',
    bonusEn:
      'Increases CRIT Rate by <b>8/10/12/14/16%</b> and increases Normal ATK SPD by 12%. Additionally, Normal and Charged Attacks hits on enemies have a 50% chance to trigger a vacuum blade that deals <b>40/55/70/85/100%</b> of ATK as DMG in a small AoE. This effect can occur no more than once every 2s.',
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: 'Primordial Jade Winged-Spear',
    nameVi: 'Hòa Phác Diên',
    typeEn: typeEn.Polearm,
    typeVi: typeVi.Polearm,
    rarity: 5,
    ATK: 48,
    secondaryVi: secondVi.CR,
    secondaryEn: secondEn.CR,
    bonusVi:
      'Khi đánh trúng kẻ địch tấn công của bản thân tăng <b>3.2/3.9/4.6/5.3/6%</b>, kéo dài 6s, có thể cộng dồn 7 tầng. Mỗi 0.3s có hiệu quả 1 lần, khi cộng dồn đầy sẽ tăng <b>12/15/18/21/24%</b> sát thương.',
    bonusEn:
      'On hit, increases ATK by <b>3.2/3.9/4.6/5.3/6%</b> for 6s. Max 7 stacks. This effect can only occur once every 0.3s. While in possession of the maximum possible stacks, DMG dealt is increased by <b>12/15/18/21/24%</b>.',
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: "Wolf's Gravestone",
    nameVi: 'Đường Cùng Của Sói',
    typeEn: typeEn.Claymore,
    typeVi: typeVi.Claymore,
    rarity: 5,
    ATK: 46,
    secondaryVi: secondVi.ATK,
    secondaryEn: secondEn.ATK,
    bonusVi:
      'Tấn công tăng <b>20/25/30/35/40%</b>. Khi tấn công đánh trúng kẻ địch có HP dưới 30%, lực tấn công của tất cả thành viên đội tăng <b>40/50/60/70/80%</b>, kéo dài 12s. Mỗi 30s mới thi triển 1 lần.',
    bonusEn:
      "Increases ATK by <b>20/25/30/35/40%</b>. On hit, attacks against enemies with less than 30% HP increase all party members' Base ATK by <b>40/50/60/70/80%</b> for 12s. Can only occur once every 30s.",
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: 'The Unforged',
    nameVi: 'Kiếm Vô Công',
    typeEn: typeEn.Claymore,
    typeVi: typeVi.Claymore,
    rarity: 5,
    ATK: 46,
    secondaryVi: secondVi.ATK,
    secondaryEn: secondEn.ATK,
    bonusVi:
      'Hiệu quả khiên tăng <b>20/25/30/35/40%</b>. Trong vòng 8s sau khi đánh trúng, tấn công tăng <b>4/5/6/7/8%</b>. Cộng dồn 5 tầng, mỗi 0.3s chỉ được thi triển 1 lần. Ngoài ra, khi được khiên bảo vệ, hiệu quả tăng tấn công sẽ tăng 100%.',
    bonusEn:
      'Increases Shield Strength by <b>20/25/30/35/40%</b>, scoring hits on opponents increases ATK by <b>4/5/6/7/8%</b> for 8s. Max 5 stacks. Can only occur once every 0.3s. While protected by a shield this ATK increase effect is increased by 100%',
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: 'Song of Broken Pines',
    nameVi: 'Tiếng Gió Trong Rừng Thông',
    typeEn: typeEn.Claymore,
    typeVi: typeVi.Claymore,
    rarity: 5,
    ATK: 46,
    secondaryVi: secondVi.PDM,
    secondaryEn: secondEn.PDM,
    bonusVi:
      'Một phần của "Ca Khúc Thời Đại Nghìn Năm" lãng du trong gió. Tấn công tăng <b>16/20/24/28/32%</b>. Khi đánh thường hoặc trọng kích trúng kẻ địch sẽ cung cấp cho nhân vật 1 Bùa Thì Thầm, mỗi 0.3s tối đa kích hoạt 1 lần.\n<br>\nKhi có 4 Bùa Thì Thầm sẽ tiêu hao tất cả, khiến tất cả nhân vật trong đội gần đó sẽ nhận được hiệu ứng "Ca Khúc Thời Đại Nghìn Năm - Khúc Ca Vén Cờ" kéo dài 12s: Tốc độ đánh thường tăng <b>12/15/18/21/24%</b>, tấn công tăng <b>20/25/30/35/40%</b>.\n<br>\nTrong 20s sau khi kích hoạt sẽ không thể nhận lại Bùa Thì Thầm. Các chỉ số cùng loại trong "Ca Khúc Thời Đại Nghìn Năm" không thể cộng dồn.	',
    bonusEn:
      'A part of the "Millennial Movement" that wanders amidst the winds. Increases ATK by <b>16/20/24/28/32%</b>, and when Normal or Charged Attacks hit opponents, the character gains a Sigil of Whispers. This effect can be triggered once every 0.3s.\n<br>\nWhen you possess four Sigils of Whispers, all of them will be consumed and all nearby party members will obtain the "Millennial Movement: Banner-Hymn" effect for 12s. "Millennial Movement: Banner-Hymn" increases Normal ATK SPD by <b>12/15/18/21/24%</b> and increases ATK by <b>20/25/30/35/40%</b>.\n<br>\nOnce this effect is triggered, you will not gain Sigils of Whispers for 20s. Of the many effects of the "Millennial Movement, " buffs of the same type will not stack.',
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: 'Skyward Pride',
    nameVi: 'Thiên Không Kiêu Ngạo',
    typeEn: typeEn.Claymore,
    typeVi: typeVi.Claymore,
    rarity: 5,
    ATK: 48,
    secondaryVi: secondVi.ER,
    secondaryEn: secondEn.ER,
    bonusVi:
      'Sát thương tạo thành tăng <b>8/10/12/14/16%</b>. Sau khi thi triển kỹ năng nộ: Khi tấn công thường và trọng kích đánh trúng địch sẽ phóng ra lưỡi dao chân không, tạo thành <b>80/100/120/140/160%</b> sát thương cho kẻ địch trên đường đi, kéo dài 20s hoặc đến khi phóng ra 8 lần dao chân không.',
    bonusEn:
      'Increases all DMG by <b>8/10/12/14/16%</b>. After using an Elemental Burst, Normal or Charged Attack, on hit, creates a vacuum blade that does <b>80/100/120/140/160%</b> Physical DMG to enemies along its path. Lasts for 20s or 8 vacuum blades.',
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: 'Skyward Atlas',
    nameVi: 'Quyển Thiên Không',
    typeEn: typeEn.Catalyst,
    typeVi: typeVi.Catalyst,
    rarity: 5,
    ATK: 48,
    secondaryVi: secondVi.ATK,
    secondaryEn: secondEn.ATK,
    bonusVi:
      'Tăng sát thương Nguyên Tố <b>12/15/18/21/24%</b>. Khi tấn công thường đánh trúng địch, có tỷ lệ 50% nhận được sự ưu ái của mây trời, trong 15s chủ động tấn công kẻ địch ở gần, tạo thành sát thương bằng <b>160/200/240/280/320%</b> lực tấn công. Mỗi 30s mới thi triển 1 lần.',
    bonusEn:
      'Increases Elemental DMG Bonus by <b>12/15/18/21/24%</b>. Normal Attack hits have a 50% chance to earn the favor of the clouds. which actively seek out nearby enemies to attack for 15s, dealing <b>160/200/240/280/320%</b> ATK DMG. Can only occur once every 30s.',
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: 'Lost Prayer to the Sacred Winds',
    nameVi: 'Điển Tích Tây Phong',
    typeEn: typeEn.Catalyst,
    typeVi: typeVi.Catalyst,
    rarity: 5,
    ATK: 44,
    secondaryVi: secondVi.CR,
    secondaryEn: secondEn.CR,
    bonusVi:
      'Tốc độ di chuyển tăng 10%. Lên trận mỗi 4s nhận <b>6/8/10/12/14%</b> buff sát thương Nguyên Tố. Cộng dồn tối đa 4 lần, kéo dài đến khi nhân vật ngã xuống hoặc rời trận.',
    bonusEn:
      'Increases Movement SPD by 10%. When in battle, earn a <b>6/8/10/12/14%</b> Elemental DMG Bonus every 4s. Max 4 stacks. Lasts until the character falls or leaves combat.',
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: 'Memory of Dust',
    nameVi: 'Khóa Trần Thế',
    typeEn: typeEn.Catalyst,
    typeVi: typeVi.Catalyst,
    rarity: 5,
    ATK: 46,
    secondaryVi: secondVi.ATK,
    secondaryEn: secondEn.ATK,
    bonusVi:
      'Hiệu quả khiên tăng <b>20/25/30/35/40%</b>. Trong vòng 8s sau khi đánh trúng, tấn công tăng <b>4/5/6/7/8%</b>. Cộng dồn 5 tầng, mỗi 0.3s chỉ được thi triển 1 lần. Ngoài ra, khi được khiên bảo vệ, hiệu quả tăng tấn công sẽ tăng 100%.',
    bonusEn:
      'Increase Shield Strength by <b>20/25/30/35/40%</b>. Scoring hits on opponents increases ATK by <b>4/5/6/7/8%</b> for 8s. Max 5 stacks. Can only occur once every 0.3s. While protected by a shield, this ATK increase effect is increased by 100%.',
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: 'Skyward Harp',
    nameVi: 'Cánh Thiên Không',
    typeEn: typeEn.Bow,
    typeVi: typeVi.Bow,
    rarity: 5,
    ATK: 48,
    secondaryVi: secondVi.CR,
    secondaryEn: secondEn.CR,
    bonusVi:
      'Sát thương bạo kích tăng <b>20/25/30/35/40%</b>. Khi đánh trúng có <b>60/70/80/90/100%</b> tỷ lệ tạo thành sát thương vật lý 125% trong phạm vi nhỏ, mỗi <b>4/3.5/3/2.5/2s</b> mới có hiệu quả một lần.',
    bonusEn:
      'Increases CRIT DMG by <b>20/25/30/35/40%</b>. Hits have a <b>60/70/80/90/100%</b> chance to inflict a small AoE attack, dealing 125% Physical ATK DMG. Can only occur once every <b>4/3.5/3/2.5/2s</b>.',
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: 'Elegy for the End',
    nameVi: 'Tiếng Thở Dài Vô Tận',
    typeEn: typeEn.Bow,
    typeVi: typeVi.Bow,
    rarity: 5,
    ATK: 46,
    secondaryVi: secondVi.ER,
    secondaryEn: secondEn.ER,
    bonusVi:
      'Một phần của "Ca Khúc Thời Đại Nghìn Năm" lãng du trong gió.<br>Tinh Thông Nguyên Tố tăng <b>60/75/90/105/120</b> điểm.<br>Khi Kỹ Năng Nguyên Tố hoặc Kỹ Năng Nộ của nhân vật dùng vũ khí này đánh trúng địch, nhân vật sẽ nhận 1 Lá Bùa Tưởng Nhớ, mỗi 0.2 giây kích hoạt nhiều nhất 1 lần, khi nhân vật ở trong đội phía sau cũng có thể kích hoạt. Khi có 4 Lá Bùa Tưởng Nhớ sẽ tiêu hao tất cả bùa, khiến tất cả nhân vật trong đội đang ở gần nhận hiệu quả "Ca Khúc Thời Đại Nghìn Năm - Bài Ca Ly Biệt": Tinh Thông Nguyên Tố tăng <b>100/125/150/175/200</b> điểm, tấn công tăng <b>20/25/30/35/40%</b> trong 12 giây. Trong vòng 20 giây sau khi kích hoạt sẽ không thể nhận Lá Bùa Tưởng Nhớ nữa. Khi các hiệu quả của "Ca Khúc Thời Đại Nghìn Năm" đang kích hoạt, những hiệu quả cùng loại khác sẽ không được cộng dồn.',
    bonusEn:
      'A part of the "Millennial Movement" that wanders amidst the winds.<br>Increases Elemental Mastery by <b>60/75/90/105/120</b>.<br>When the Elemental Skills or Elemental Bursts of the character wielding this weapon hit opponents, that character gains a Sigil of Remembrance. This effect can be triggered once every 0.2s and can be triggered even if said character is not on the field. When you possess 4 Sigils of Remembrance, all of them will be consumed and all nearby party members will obtain the "Millennial Movement: Farewell Song" effect for 12s. "Millennial Movement: Farewell Song" increases Elemental Mastery by <b>100/125/150/175/200</b> and increases ATK by <b>20/25/30/35/40%</b>. Once this effect is triggered, you will not gain Sigils of Remembrance for 20s. Of the many effects of the "Millennial Movement" buffs of the same type will not stack.',
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: "Amos' Bow",
    nameVi: 'Cung Amos',
    typeEn: typeEn.Bow,
    typeVi: typeVi.Bow,
    rarity: 5,
    ATK: 46,
    secondaryVi: secondVi.ATK,
    secondaryEn: secondEn.ATK,
    bonusVi:
      'Tăng <b>12/15/18/21/24%</b> sát thương của tấn công thường và trọng kích. Tấn công thường và trọng kích mỗi 0.1s sau khi bắn tên, sát thương sẽ tăng <b>8/10/12/14/16%</b>, tối đa tăng 5 lần.',
    bonusEn:
      'Increases Normal Attack and Aimed Shot DMG by <b>12/15/18/21/24%</b>. Increases DMG from arrows shot by a further <b>8/10/12/14/16%</b> for every 0.1s that the arrow is in flight, up to 0.5s. Stacks up to 5 times on each arrow.',
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: 'The Flute',
    nameVi: 'Kiếm Sáo',
    typeEn: typeEn.Sword,
    typeVi: typeVi.Sword,
    rarity: 4,
    ATK: 42,
    secondaryVi: secondVi.ATK,
    secondaryEn: secondEn.ATK,
    bonusVi:
      'Khi tấn công thường hoặc trọng kích đánh trúng địch, sẽ nhận 1 hợp âm. Sau khi tích lũy đủ 5 hợp âm, phát ra sức mạnh của âm luật, tạo thành <b>100/125/150/175/200%</b> sát thương công kích cho kẻ địch xung quanh. Hợp âm có thể tồn lại lâu nhất 30s, mỗi 0.5s nhiều nhất có thể nhận 1 hợp âm.',
    bonusEn:
      'Normal or Charged Attacks grant Harmonic on hits. Gaining 5 Harmonics triggers the power of music and deals <b>100/125/150/175/200%</b> ATK DMG to surrounding enemies. Harmonics last up to 30s, and a maximum of 1 can be gained every 0.5s.',
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: 'The Black Sword',
    nameVi: 'Kiếm Đen',
    typeEn: typeEn.Sword,
    typeVi: typeVi.Sword,
    rarity: 4,
    ATK: 42,
    secondaryVi: secondVi.CR,
    secondaryEn: secondEn.CR,
    bonusVi:
      'Tấn công thường và sát thương trọng kích tăng  <b>20/25/30/35/40%</b>.\n<br>\nNgoài ra khi tấn công thường và bạo kích trọng kích sẽ hồi HP bằng <b>60/70/80/90/100%</b> tấn công. Hiệu quả này mỗi 5s thi triển 1 lần.',
    bonusEn:
      'Increases DMG dealt by Normal and Charged Attacks by <b>20/25/30/35/40%</b>.\n<br>\nAdditionally, regenerates <b>60/70/80/90/100%</b> of ATK as HP when Normal and Charged Attacks score a CRIT Hit. This effect can occur once every 5s.',
    locationEn: 'BP Bounty',
    locationVi: 'Thưởng BP',
  },
  {
    nameEn: 'The Alley Flash',
    nameVi: 'Tia Sáng Nơi Hẻm Tối',
    typeEn: typeEn.Sword,
    typeVi: typeVi.Sword,
    rarity: 4,
    ATK: 45,
    secondaryVi: secondVi.EM,
    secondaryEn: secondEn.EM,
    bonusVi:
      'Sát thương nhân vật tạo thành tăng <b>12/15/18/21/24%</b>. Sau khi chịu phải sát thương, hiệu quả tăng sát thương này sẽ mất hiệu lực 5s.',
    bonusEn:
      'Increases DMG dealt by the character equipping this weapon by <b>12/15/18/21/24%</b>. Taking DMG disables this effect for 5s.',
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: 'Sword of Descension',
    nameVi: 'Kiếm Giáng Lâm',
    typeEn: typeEn.Sword,
    typeVi: typeVi.Sword,
    rarity: 4,
    ATK: 39,
    secondaryVi: secondVi.ATK,
    secondaryEn: secondEn.ATK,
    bonusVi:
      'Sau khi tấn công thường và trọng kích đánh trúng kẻ địch có tỷ lệ 50% tạo thành 200% sát thương tấn công trong phạm vi nhỏ. Hiệu quả này mỗi 10s chỉ thi triển 1 lần. Ngoài ra, Nhà Lữ Hành có trang bị Kiếm Giáng Lâm thì tấn công sẽ tăng 66 điểm.	',
    bonusEn:
      'Hitting enemies with Normal or Charged Attacks grants a 50% chance to deal 200% ATK as DMG in a small AoE. This effect can only occur once every 10s. Additionally, if the Traveler equips the Sword of Descension, their ATK is increased by 66.',
    locationEn: 'Exclusive to PS',
    locationVi: 'Độc quyền PS',
  },
  {
    nameEn: 'Sacrificial Sword',
    nameVi: 'Kiếm Tế Lễ',
    typeEn: typeEn.Sword,
    typeVi: typeVi.Sword,
    rarity: 4,
    ATK: 41,
    secondaryVi: secondVi.ER,
    secondaryEn: secondEn.ER,
    bonusVi:
      'Khi kỹ năng Nguyên Tố tạo thành sát thương, có tỷ lệ <b>40/50/60/70/80%</b> làm mới thời gian CD kỹ năng đó, mỗi <b>30/26/22/18/14s</b> mới thi triển 1 lần.',
    bonusEn:
      'After damaging an opponent with an Elemental Skill, the skill has a <b>40/50/60/70/80%</b> chance to end its own CD. Can only occur once every <b>30/26/22/18/14s</b>.',
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: 'Royal Longsword',
    nameVi: 'Trường Kiếm Tông Thất',
    typeEn: typeEn.Sword,
    typeVi: typeVi.Sword,
    rarity: 4,
    ATK: 42,
    secondaryVi: secondVi.ATK,
    secondaryEn: secondEn.ATK,
    bonusVi:
      'Khi tấn công tạo thành sát thương, tăng tỷ lệ bạo kích <b>8/10/12/14/16%</b>, nhiều nhất cộng dồn 5 lần. Sau khi tấn công tạo thành bạo kích, xóa hiệu quả Chuyên Chú đã có.',
    bonusEn:
      'Upon damaging an enemy, increases CRIT Rate by <b>8/10/12/14/16%</b>. Max 5 stacks. A CRIT hit removes all stacks.',
    locationEn: 'Starglitter Exchange',
    locationVi: 'Đổi Tinh Huy',
  },
  {
    nameEn: 'Prototype Rancour',
    nameVi: 'Mẫu Trảm Nham',
    typeEn: typeEn.Sword,
    typeVi: typeVi.Sword,
    rarity: 4,
    ATK: 44,
    secondaryVi: secondVi.PDM,
    secondaryEn: secondEn.PDM,
    bonusVi:
      'Khi tấn công thường hoặc trọng kích đánh trúng địch, tấn công và phòng ngự tăng <b>4/4.5/5/5.5/6%</b>, kéo dài 6s, tối đa cộng dồn 4 lần. Mỗi 0.3s mới thi triển 1 lần.',
    bonusEn:
      'On hit, Normal or Charged Attacks increase Base ATK and DEF by <b>4/4.5/5/5.5/6%</b> for 6s. Max 4 stacks. Can only occur once every 0.3s.',
    locationEn: 'Crafting',
    locationVi: 'Rèn',
  },
  {
    nameEn: "Lion's Roar",
    nameVi: 'Tiếng Hét Của Rồng',
    typeEn: typeEn.Sword,
    typeVi: typeVi.Sword,
    rarity: 4,
    ATK: 42,
    secondaryVi: secondVi.ATK,
    secondaryEn: secondEn.ATK,
    bonusVi:
      'Sát thương tạo ra cho kẻ địch bị ảnh hưởng bởi Nguyên Tố<span class="pyro"> Hỏa </span>hoặc<span class="electro"> Lôi </span>tăng <b>20/24/28/32/36%</b>.',
    bonusEn:
      'Increases DMG against enemies affected by<span class="pyro"> Pyro </span>or<span class="electro"> Electro </span>by <b>20/24/28/32/36%</b>.',
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: 'Iron Sting',
    nameVi: 'Thiết Phong Kích',
    typeEn: typeEn.Sword,
    typeVi: typeVi.Sword,
    rarity: 4,
    ATK: 42,
    secondaryVi: secondVi.EM,
    secondaryEn: secondEn.EM,
    bonusVi:
      'Trong 6s sau khi tạo thành sát thương nguyên tố, sát thương nhân vật tạo ra tăng <b>6/7.5/9/10.5/12%</b>, cộng dồn 2 lần. Mỗi 1s mới thi triển 1 lần.',
    bonusEn:
      'Dealing Elemental DMG increases all DMG by <b>6/7.5/9/10.5/12%</b> for 6s. Max 2 stacks. Can only occur once every 1s.',
    locationEn: 'Crafting',
    locationVi: 'Rèn',
  },
  {
    nameEn: 'Festering Desire',
    nameVi: 'Răng Nanh Rỉ Sét',
    typeEn: typeEn.Sword,
    typeVi: typeVi.Sword,
    rarity: 4,
    ATK: 42,
    secondaryVi: secondVi.EM,
    secondaryEn: secondEn.EM,
    bonusVi:
      'Tăng <b>16/20/24/28/32%</b> sát thương kỹ năng nguyên tố, tăng <b>6/7.5/9/10.5/12%</b> tỷ lệ bạo kích của kỹ năng nguyên tố.',
    bonusEn:
      'Increases Elemental Skill DMG by <b>16/20/24/28/32%</b> and Elemental Skill CRIT Rate by <b>6/7.5/9/10.5/12%</b>.',
    locationEn: 'Story Quest',
    locationVi: 'Nhiệm vụ Sự kiện',
  },
  {
    nameEn: 'Favonius Sword',
    nameVi: 'Tây Phong Kiếm',
    typeEn: typeEn.Sword,
    typeVi: typeVi.Sword,
    rarity: 4,
    ATK: 41,
    secondaryVi: secondVi.ER,
    secondaryEn: secondEn.ER,
    bonusVi:
      'Khi tạo thành bạo kích có tỷ lệ <b>60/70/80/90/100%</b> sinh ra một lượng nhỏ Nguyên Tố Hạt Nhân, khôi phục 6 Năng Lượng Nguyên Tố cho nhân vật. Mỗi <b>12/10.5/9/7.5/6s</b> mới thi triển 1 lần.',
    bonusEn:
      'CRIT hits have a <b>60/70/80/90/100%</b> chance to generate 1 Elemental Orb, which will regenerate 6 Energy for the character. Can only occur once every <b>12/10.5/9/7.5/6s</b>.',
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: 'Blackcliff Longsword',
    nameVi: 'Hắc Nham Trường Kiếm',
    typeEn: typeEn.Sword,
    typeVi: typeVi.Sword,
    rarity: 4,
    ATK: 44,
    secondaryVi: secondVi.CD,
    secondaryEn: secondEn.CD,
    bonusVi:
      'Sau khi đánh bại kẻ địch, tấn công tăng <b>12/15/18/21/24%</b>, kéo dài 30s. Hiệu quả này cộng dồn đến 3 tầng, CD mỗi tầng độc lập.',
    bonusEn:
      'After defeating an enemy, ATK is increased by <b>12/15/18/21/24%</b> for 30s. This effect has a maximum of 3 stacks, and the duration of each stack is independent of the others.',
    locationEn: 'Starglitter Exchange',
    locationVi: 'Đổi Tinh Huy',
  },
  {
    nameEn: 'Royal Spear',
    nameVi: 'Thương Săn Tông Thất',
    typeEn: typeEn.Polearm,
    typeVi: typeVi.Polearm,
    rarity: 4,
    ATK: 44,
    secondaryVi: secondVi.ATK,
    secondaryEn: secondEn.ATK,
    bonusVi:
      'Khi tấn công tạo thành sát thương, tăng tỷ lệ bạo kích <b>8/10/12/14/16%</b>, nhiều nhất cộng dồn 5 lần. Sau khi tấn công tạo thành bạo kích, xóa hiệu quả Chuyên Chú đã có.',
    bonusEn:
      'Upon damaging an opponent, increases CRIT Rate by <b>8/10/12/14/16%</b>. Max 5 stacks. A CRIT hit removes all stacks.',
    locationEn: 'Starglitter Exchange',
    locationVi: 'Đổi Tinh Huy',
  },
  {
    nameEn: 'Prototype Grudge',
    nameVi: 'Mẫu Tinh Liêm',
    typeEn: typeEn.Polearm,
    typeVi: typeVi.Polearm,
    rarity: 4,
    ATK: 42,
    secondaryVi: secondVi.ER,
    secondaryEn: secondEn.ER,
    bonusVi:
      'Sau khi thi triển kỹ năng nguyên tố, sát thương tấn công thường và trọng kích tăng <b>8/10/12/14/16%</b>. Kéo dài 12s, tối đa cộng dồn 2 tầng.',
    bonusEn:
      'After using an Elemental Skill, increases Normal and Charged Attack DMG by <b>8/10/12/14/16%</b> for 12s. Max 2 stacks.',
    locationEn: 'Crafting',
    locationVi: 'Rèn',
  },
  {
    nameEn: 'Lithic Spear',
    nameVi: 'Thương Thiên Nham',
    typeEn: typeEn.Polearm,
    typeVi: typeVi.Polearm,
    rarity: 4,
    ATK: 44,
    secondaryVi: secondVi.ATK,
    secondaryEn: secondEn.ATK,
    bonusVi:
      'Mỗi khi trong đội có 1 nhân vật Liyue, nhân vật trang bị vũ khí này sẽ nhận <b>7/8/9/10/11%</b> tăng tấn công và <b>3/4/5/6/7%</b> tăng tỷ lệ bạo kích. Nhiều nhất có thể nhận 4 tầng hiệu quả tăng.',
    bonusEn:
      'For every characters who hails from Liyue, the characters who equips this weapon gains <b>7/8/9/10/11%</b> ATK increase and a <b>3/4/5/6/7%</b> CRIT Rate increase. This effect stacks up to 4 times.',
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: 'Favonius Lance',
    nameVi: 'Thương Tây Phong',
    typeEn: typeEn.Polearm,
    typeVi: typeVi.Polearm,
    rarity: 4,
    ATK: 44,
    secondaryVi: secondVi.ER,
    secondaryEn: secondEn.ER,
    bonusVi:
      'Khi tạo thành bạo kích có tỷ lệ <b>60/70/80/90/100%</b> sinh ra một lượng nhỏ Nguyên Tố Hạt Nhân, khôi phục 6 Năng Lượng Nguyên Tố cho nhân vật. Mỗi <b>12/10.5/9/7.5/6s</b> mới thi triển 1 lần.',
    bonusEn:
      'CRIT hits have a <b>60/70/80/90/100%</b> chance to generate 1 Elemental Orb, which will regenerate 6 Energy for the character. Can only occur once every <b>12/10.5/9/7.5/6s</b>.',
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: "Dragon's Bane",
    nameVi: 'Tai Ương Của Rồng',
    typeEn: typeEn.Polearm,
    typeVi: typeVi.Polearm,
    rarity: 4,
    ATK: 41,
    secondaryVi: secondVi.EM,
    secondaryEn: secondEn.EM,
    bonusVi:
      'Sát thương tạo ra cho kẻ địch bị ảnh hưởng bởi Nguyên Tố<span class="hydro"> Thủy </span>hoặc<span class="pyro"> Hỏa </span>tăng <b>20/24/28/32/36%</b>.',
    bonusEn:
      'Increases DMG against enemies affected by<span class="hydro"> Hydro </span>or<span class="pyro"> Pyro </span>by <b>20/24/28/32/36%</b>.',
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: 'Dragonspine Spear',
    nameVi: 'Thương Long Tích',
    typeEn: typeEn.Polearm,
    typeVi: typeVi.Polearm,
    rarity: 4,
    ATK: 41,
    secondaryVi: secondVi.PDM,
    secondaryEn: secondEn.PDM,
    bonusVi:
      'Khi tấn công thường và trọng kích đánh trúng kẻ địch có tỷ lệ <b>60/70/80/90/100%</b> tạo ra Đá Vĩnh Hằng phía trên kẻ địch và rơi xuống, gây sát thương phạm vi bằng <b>80/95/110/125/140%</b> tấn công.\n<br>\nNếu địch bị ảnh hưởng bởi nguyên tố<span class="cryo"> Băng</span>, sẽ gây sát thương bằng <b>200/240/280/320/360%</b> tấn công. Hiệu quả này mỗi 10s kích hoạt 1 lần.',
    bonusEn:
      'Hitting an opponent with Normal and Charged Attacks has a <b>60/70/80/90/100%</b> chance of forming and dropping an Everfrost Icicle above them, dealing <b>80/95/110/125/140%</b> AoE ATK DMG.\n<br>\nOpponents affected by<span class="cryo"> Cryo </span>are dealt <b>200/240/280/320/360%</b> ATK DMG. Can only occur once every 10s.',
    locationEn: 'Crafting',
    locationVi: 'Rèn',
  },
  {
    nameEn: 'Deathmatch',
    nameVi: 'Thương Quyết Chiến',
    typeEn: typeEn.Polearm,
    typeVi: typeVi.Polearm,
    rarity: 4,
    ATK: 41,
    secondaryVi: secondVi.CR,
    secondaryEn: secondEn.CR,
    bonusVi:
      'Khi bên cạnh có ít nhất 2 kẻ địch, được tăng <b>16/20/24/28/32%</b> tấn công và <b>16/20/24/28/32%</b> phòng ngự, khi có dưới 2 kẻ địch, được tăng <b>24/30/36/42/48%</b> tấn công.',
    bonusEn:
      'If there are at least 2 opponents nearby, ATK is increased by <b>16/20/24/28/32%</b> and DEF is increased by <b>16/20/24/28/32%</b>. If there are less than 2 enemies nearby, ATK is increased by <b>24/30/36/42/48%</b>.',
    locationEn: 'BP Bounty',
    locationVi: 'Thưởng BP',
  },
  {
    nameEn: 'Crescent Pike',
    nameVi: 'Lưu Nguyệt Châm',
    typeEn: typeEn.Polearm,
    typeVi: typeVi.Polearm,
    rarity: 4,
    ATK: 44,
    secondaryVi: secondVi.PDM,
    secondaryEn: secondEn.PDM,
    bonusVi:
      'Trong 5s sau khi nhận Nguyên Tố Hạt Nhân hoặc Nguyên Tố Tinh Cầu, tấn công thường và trọng kích sẽ tạo thêm sát thương bằng <b>20/25/30/35/40%</b> tấn công.',
    bonusEn:
      'After picking up an Elemental Orb/Particle, Normal and Charged Attacks deal an additional <b>20/25/30/35/40%</b> ATK as DMG for 5s.',
    locationEn: 'Crafting',
    locationVi: 'Rèn',
  },
  {
    nameEn: 'Blackcliff Pole',
    nameVi: 'Thương Hắc Nham',
    typeEn: typeEn.Polearm,
    typeVi: typeVi.Polearm,
    rarity: 4,
    ATK: 42,
    secondaryVi: secondVi.CD,
    secondaryEn: secondEn.CD,
    bonusVi:
      'Sau khi đánh bại kẻ địch, tấn công tăng <b>12/15/18/21/24%</b>, kéo dài 30s. Hiệu quả này cộng dồn đến 3 tầng, CD mỗi tầng độc lập.',
    bonusEn:
      'After defeating an enemy, ATK is increased by <b>12/15/18/21/24%</b> for 30s. This effect has a maximum of 3 stacks, and the duration of each stack is independent of the others.',
    locationEn: 'Starglitter Exchange',
    locationVi: 'Đổi Tinh Huy',
  },
  {
    nameEn: 'Whiteblind',
    nameVi: 'Kiếm Bạch Ảnh',
    typeEn: typeEn.Claymore,
    typeVi: typeVi.Claymore,
    rarity: 4,
    ATK: 42,
    secondaryVi: secondVi.DEF,
    secondaryEn: secondEn.DEF,
    bonusVi:
      'Sau khi tấn công thường và trọng kích đánh trúng địch, tấn công và phòng ngự tăng <b>6/7.5/9/10.5/12%</b>. Kéo dài 6s, tối đa cộng dồn 4 lần. Mỗi 0.5s mới thi triển 1 lần.',
    bonusEn:
      'On hit, Normal or Charged Attacks increase Base ATK and DEF by <b>6/7.5/9/10.5/12%</b> for 6s. Max 4 stacks. Can only occur once every 0.5s.',
    locationEn: 'Crafting',
    locationVi: 'Rèn',
  },
  {
    nameEn: 'The Bell',
    nameVi: 'Kiếm Chuông',
    typeEn: typeEn.Claymore,
    typeVi: typeVi.Claymore,
    rarity: 4,
    ATK: 42,
    secondaryVi: secondVi.HP,
    secondaryEn: secondEn.HP,
    bonusVi:
      'Khi nhận sát thương sẽ tạo ra khiên có lượng hấp thụ sát thương bằng <b>20/23/26/29/32%</b> giới hạn HP, kéo dài 10s hoặc đến khi khiên mất hiệu lực, mỗi 45s chỉ thi triển 1 lần. Khi nhân vật được khiên bảo vệ, sát thương tạo thành tăng <b>12/15/18/21/24%</b>.',
    bonusEn:
      'Taking DMG generates a shield which absorbs DMG up to <b>20/23/26/29/32%</b> of Max HP. This shield lasts for 10s or until broken, and can only be triggered once every 45s. While protected by the shield, the character gains <b>12/15/18/21/24%</b> increased DMG.',
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: 'Snow-Tombed Starsilver',
    nameVi: 'Tuyết Vùi Tinh Ngân',
    typeEn: typeEn.Claymore,
    typeVi: typeVi.Claymore,
    rarity: 4,
    ATK: 44,
    secondaryVi: secondVi.PDM,
    secondaryEn: secondEn.PDM,
    bonusVi:
      'Khi tấn công thường và trọng kích đánh trúng kẻ địch có tỷ lệ <b>60/70/80/90/100%</b> tạo ra Đá Vĩnh Hằng phía trên kẻ địch và rơi xuống, gây sát thương phạm vi bằng <b>80/95/110/125/140%</b> tấn công.\n<br>\nNếu địch bị ảnh hưởng bởi nguyên tố<span class="cryo"> Băng</span>, sẽ gây sát thương bằng <b>200/240/280/320/360%</b> tấn công. Hiệu quả này mỗi 10s kích hoạt 1 lần.',
    bonusEn:
      'Hitting an opponent with Normal and Charged Attacks has a <b>60/70/80/90/100%</b> chance of forming and dropping an Everfrost Icicle above them, dealing <b>80/95/110/125/140%</b> AoE ATK DMG.\n<br>\nOpponents affected by<span class="cryo"> Cryo </span>are dealt <b>200/240/280/320/360%</b> ATK DMG. Can only occur once every 10s.',
    locationEn: 'Crafting',
    locationVi: 'Rèn',
  },
  {
    nameEn: 'Serpent Spine',
    nameVi: 'Kiếm Li Cốt',
    typeEn: typeEn.Claymore,
    typeVi: typeVi.Claymore,
    rarity: 4,
    ATK: 42,
    secondaryVi: secondVi.CR,
    secondaryEn: secondEn.CR,
    bonusVi:
      'Khi nhân vật ra trận, mỗi 4s tăng <b>6/7/8/9/10%</b> sát thương gây ra, <b>3/2.7/2.4/2.1/1.8%</b> sát thương phải chịu. Cộng dồn tối đa 5 tầng, không làm mới khi nhân vật rời khỏi trận, sau khi chịu sát thương sẽ giảm 1 tầng hiệu quả.',
    bonusEn:
      'Every 4s a character is on the field, they will deal <b>6/7/8/9/10%</b> more DMG and take <b>3/2.7/2.4/2.1/1.8%</b> more DMG. This effect has a maximum of 5 stacks and will not be reset if the character leaves the field, but will be cleared when the character takes DMG.',
    locationEn: 'BP Bounty',
    locationVi: 'Thưởng BP',
  },
  {
    nameEn: 'Sacrificial Greatsword',
    nameVi: 'Đại Kiếm Tế Lễ',
    typeEn: typeEn.Claymore,
    typeVi: typeVi.Claymore,
    rarity: 4,
    ATK: 44,
    secondaryVi: secondVi.ER,
    secondaryEn: secondEn.ER,
    bonusVi:
      'Khi kỹ năng Nguyên Tố tạo thành sát thương, có tỷ lệ <b>40/50/60/70/80%</b> làm mới thời gian CD kỹ năng đó, mỗi <b>30/26/22/18/14s</b> mới thi triển 1 lần.',
    bonusEn:
      'After damaging an opponent with an Elemental Skill, the skill has a <b>40/50/60/70/80%</b> chance to end its own CD. Can only occur once every <b>30/26/22/18/14s</b>.',
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: 'Royal Greatsword',
    nameVi: 'Đại Kiếm Tông Thất',
    typeEn: typeEn.Claymore,
    typeVi: typeVi.Claymore,
    rarity: 4,
    ATK: 44,
    secondaryVi: secondVi.ATK,
    secondaryEn: secondEn.ATK,
    bonusVi:
      'Khi tấn công tạo thành sát thương, tăng tỷ lệ bạo kích <b>8/10/12/14/16%</b>, nhiều nhất cộng dồn 5 lần. Sau khi tấn công tạo thành bạo kích, xóa hiệu quả Chuyên Chú đã có.',
    bonusEn:
      'Upon damaging an enemy, increases CRIT Rate by <b>8/10/12/14/16%</b>. Max 5 stacks. A CRIT hit removes all stacks.',
    locationEn: 'Starglitter Exchange',
    locationVi: 'Đổi Tinh Huy',
  },
  {
    nameEn: 'Rainslasher',
    nameVi: 'Vũ Tài',
    typeEn: typeEn.Claymore,
    typeVi: typeVi.Claymore,
    rarity: 4,
    ATK: 42,
    secondaryVi: secondVi.EM,
    secondaryEn: secondEn.EM,
    bonusVi:
      'Sát thương tạo ra cho kẻ địch bị ảnh hưởng bởi Nguyên Tố<span class="hydro"> Thủy </span>hoặc<span class="electro"> Lôi </span>tăng <b>20/25/30/35/40%</b>.',
    bonusEn:
      'Increases DMG against enemies affected by<span class="hydro"> Hydro </span>or<span class="electro"> Electro </span>by <b>20/25/30/35/40%</b>.',
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: 'Prototype Aminus',
    nameVi: 'Mẫu Cổ Hoa',
    typeEn: typeEn.Claymore,
    typeVi: typeVi.Claymore,
    rarity: 4,
    ATK: 44,
    secondaryVi: secondVi.ATK,
    secondaryEn: secondEn.ATK,
    bonusVi:
      'Khi tấn công thường và trọng kích đánh trúng địch, có tỷ lệ 50% tạo thành <b>240/300/360/420/480%</b> sát thương thêm trong phạm vi nhỏ. Mỗi 15s mới thi triển 1 lần.',
    bonusEn:
      'On hit, Normal or Charged Attacks have a 50% chance to deal an additional <b>240/300/360/420/480%</b> ATK DMG to enemies within a small radius. Can only occur once every 15s.',
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: 'Lithic Blade',
    nameVi: 'Thiên Nham Cổ Kiếm',
    typeEn: typeEn.Claymore,
    typeVi: typeVi.Claymore,
    rarity: 4,
    ATK: 42,
    secondaryVi: secondVi.ATK,
    secondaryEn: secondEn.ATK,
    bonusVi:
      'Mỗi khi trong đội có 1 nhân vật Liyue, nhân vật trang bị vũ khí này sẽ nhận <b>7/8/9/10/11%</b> tăng tấn công và <b>3/4/5/6/7%</b> tăng tỷ lệ bạo kích. Nhiều nhất có thể nhận 4 tầng hiệu quả tăng.',
    bonusEn:
      'For every characters who hails from Liyue, the characters who equips this weapon gains <b>7/8/9/10/11%</b> ATK increase and a <b>3/4/5/6/7%</b> CRIT Rate increase. This effect stacks up to 4 times.',
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: 'Favonius Greatsword',
    nameVi: 'Đại Kiếm Tây Phong',
    typeEn: typeEn.Claymore,
    typeVi: typeVi.Claymore,
    rarity: 4,
    ATK: 41,
    secondaryVi: secondVi.ER,
    secondaryEn: secondEn.ER,
    bonusVi:
      'Khi tạo thành bạo kích có tỷ lệ <b>60/70/80/90/100%</b> sinh ra một lượng nhỏ Nguyên Tố Hạt Nhân, khôi phục 6 Năng Lượng Nguyên Tố cho nhân vật. Mỗi <b>12/10.5/9/7.5/6s</b> mới thi triển 1 lần.',
    bonusEn:
      'CRIT hits have a <b>60/70/80/90/100%</b> chance to generate 1 Elemental Orb, which will regenerate 6 Energy for the character. Can only occur once every <b>12/10.5/9/7.5/6s</b>.',
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: 'Blackcliff Slasher',
    nameVi: 'Hắc Nham Trảm Đao',
    typeEn: typeEn.Claymore,
    typeVi: typeVi.Claymore,
    rarity: 4,
    ATK: 42,
    secondaryVi: secondVi.CD,
    secondaryEn: secondEn.CD,
    bonusVi:
      'Sau khi đánh bại kẻ địch, tấn công tăng <b>12/15/18/21/24%</b>, kéo dài 30s. Hiệu quả này cộng dồn đến 3 tầng, CD mỗi tầng độc lập.',
    bonusEn:
      'After defeating an enemy, ATK is increased by <b>12/15/18/21/24%</b> for 30s. This effect has a maximum of 3 stacks, and the duration of each stack is independent of the others.',
    locationEn: 'Starglitter Exchange',
    locationVi: 'Đổi Tinh Huy',
  },
  {
    nameEn: 'Wine and Song',
    nameVi: 'Rượu Và Thơ Nơi Hẻm Tối',
    typeEn: typeEn.Catalyst,
    typeVi: typeVi.Catalyst,
    rarity: 4,
    ATK: 44,
    secondaryVi: secondVi.ER,
    secondaryEn: secondEn.ER,
    bonusVi:
      'Sau khi đánh thường trúng kẻ địch, thể lực tiêu hao của xung kích hoặc kỹ năng thay thế của xung kích giảm <b>14/16/18/20/22%</b>, kéo dài 5s. Ngoài ra, sau khi dùng xung kích hoặc kỹ năng thay thế của xung kích, tấn công tăng <b>20/25/30/35/40%</b>, kéo dài 5s.',
    bonusEn:
      'Hitting an opponent with a Normal Attack decreases the Stamina consumption of Sprint or Alternate Sprint by 14% for 5s. Additionally, using a Sprint or Alternate Sprint ability increases ATK by 20% for 5s.',
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: 'The Widsith',
    nameVi: 'Chương Nhạc Lang Thang',
    typeEn: typeEn.Catalyst,
    typeVi: typeVi.Catalyst,
    rarity: 4,
    ATK: 42,
    secondaryVi: secondVi.CD,
    secondaryEn: secondEn.CD,
    bonusVi:
      'Khi nhân vật ra trận, ngẫu nhiên nhận 1 ca khúc, kéo dài 10s. Mỗi 30s mới thi triển 1 lần. <br>\nNhạc dạo: Tấn công tăng <b>60/75/90/105/120%</b>.<br>\nĐiệp khúc: Toàn bộ sát thương nguyên tố tăng <b>48/60/72/84/96%</b>.<br>\nKhúc nhạc ngắn: Tinh thông nguyên tố tăng <b>240/300/360/420/480</b>.',
    bonusEn:
      'When a character takes the field, they will gain a random theme song for 10s. This can only occur once every 30s.<br>\nRecitative: Increases Base ATK by <b>60/75/90/105/120%</b><br>\nAria: Increases all Elemental DMG by <b>48/60/72/84/96%</b><br>\nInterlude: Elemental Mastery is increased by <b>240/300/360/420/480</b>',
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: 'Solar Pearl',
    nameVi: 'Nhật Nguyệt Hạp',
    typeEn: typeEn.Catalyst,
    typeVi: typeVi.Catalyst,
    rarity: 4,
    ATK: 42,
    secondaryVi: secondVi.CR,
    secondaryEn: secondEn.CR,
    bonusVi:
      'Trong 6s sau khi tấn công thường đánh trúng địch, sát thương kỹ năng Nguyên Tố và kỹ năng nộ tăng <b>20/25/30/35/40%</b>. Trong 6s sau khi kỹ năng nguyên tố và kỹ năng nộ đánh trúng địch, sát thương tấn công thường tăng <b>20/25/30/35/40%</b>.',
    bonusEn:
      'Normal Attack hits increase Elemental Skill and Elemental Burst DMG by <b>20/25/30/35/40%</b> for 6s. Likewise, Elemental Skill or Elemental Burst hits increase Normal Attack DMG by <b>20/25/30/35/40%</b> for 6s.',
    locationEn: 'BP Bounty',
    locationVi: 'Thưởng BP',
  },
  {
    nameEn: 'Sacrificial Fragments',
    nameVi: 'Mảnh Chương Tế Lễ',
    typeEn: typeEn.Catalyst,
    typeVi: typeVi.Catalyst,
    rarity: 4,
    ATK: 41,
    secondaryVi: secondVi.ER,
    secondaryEn: secondEn.ER,
    bonusVi:
      'Khi kỹ năng Nguyên Tố tạo thành sát thương, có tỷ lệ <b>40/50/60/70/80%</b> làm mới thời gian CD kỹ năng đó, mỗi <b>30/26/22/18/14s</b> mới thi triển 1 lần.',
    bonusEn:
      'After damaging an opponent with an Elemental Skill, the skill has a <b>40/50/60/70/80%</b> chance to end its own CD. Can only occur once every <b>30/26/22/18/14s</b>.',
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: 'Royal Grimoire',
    nameVi: 'Mật Pháp Tông Thất',
    typeEn: typeEn.Catalyst,
    typeVi: typeVi.Catalyst,
    rarity: 4,
    ATK: 44,
    secondaryVi: secondVi.ATK,
    secondaryEn: secondEn.ATK,
    bonusVi:
      'Khi tấn công tạo thành sát thương, tăng tỷ lệ bạo kích <b>8/10/12/14/16%</b>, nhiều nhất cộng dồn 5 lần. Sau khi tấn công tạo thành bạo kích, xóa hiệu quả Chuyên Chú đã có.',
    bonusEn:
      'Upon damaging an enemy, increases CRIT Rate by <b>8/10/12/14/16%</b>. Max 5 stacks. A CRIT hit removes all stacks.',
    locationEn: 'Starglitter Exchange',
    locationVi: 'Đổi Tinh Huy',
  },
  {
    nameEn: 'Prototype Malice',
    nameVi: 'Mẫu Kim Phách',
    typeEn: typeEn.Catalyst,
    typeVi: typeVi.Catalyst,
    rarity: 4,
    ATK: 42,
    secondaryVi: secondVi.HP,
    secondaryEn: secondEn.HP,
    bonusVi:
      '6s sau khi thi triển kỹ năng nộ, mỗi 2s hồi <b>4/4.5/5/5.5/6</b> điểm năng lượng nguyên tố. Tất cả nhân vật trong đội mỗi 2s hồi <b>4/4.5/5/5.5/6%</b> HP.',
    bonusEn:
      'Using an Elemental Burst regenerates <b>4/4.5/5/5.5/6</b> Energy every 2s for 6s. Additionally, all party members will regenerate <b>4/4.5/5/5.5/6%</b> HP every 2s for this duration.',
    locationEn: 'Crafting',
    locationVi: 'Rèn',
  },
  {
    nameEn: 'Mappa Mare',
    nameVi: 'Hải Đồ Vạn Quốc',
    typeEn: typeEn.Catalyst,
    typeVi: typeVi.Catalyst,
    rarity: 4,
    ATK: 44,
    secondaryVi: secondVi.EM,
    secondaryEn: secondEn.EM,
    bonusVi:
      'Trong 10s sau khi kích hoạt phản ứng Nguyên Tố, nhận <b>8/10/12/14/16%</b> buff sát thương Nguyên Tố, cộng dồn 2 tầng.',
    bonusEn:
      'Triggering an Elemental reaction grants a <b>8/10/12/14/16%</b> Elemental DMG Bonus for 10s. Max 2 stacks.',
    locationEn: 'Crafting',
    locationVi: 'Rèn',
  },
  {
    nameEn: 'Frostbearer',
    nameVi: 'Trái Chịu Lạnh',
    typeEn: typeEn.Catalyst,
    typeVi: typeVi.Catalyst,
    rarity: 4,
    ATK: 42,
    secondaryVi: secondVi.ATK,
    secondaryEn: secondEn.ATK,
    bonusVi:
      'Khi tấn công thường và trọng kích đánh trúng kẻ địch có tỷ lệ <b>60/70/80/90/100%</b> tạo ra Đá Vĩnh Hằng phía trên kẻ địch và rơi xuống, gây sát thương phạm vi bằng <b>80/95/110/125/140%</b> tấn công.\n<br>\nNếu địch bị ảnh hưởng bởi nguyên tố<span class="cryo"> Băng</span>, sẽ gây sát thương bằng <b>200/240/280/320/360%</b> tấn công. Hiệu quả này mỗi 10s kích hoạt 1 lần.',
    bonusEn:
      'Hitting an opponent with Normal and Charged Attacks has a <b>60/70/80/90/100%</b> chance of forming and dropping an Everfrost Icicle above them, dealing <b>80/95/110/125/140%</b> AoE ATK DMG.\n<br>\nOpponents affected by<span class="cryo"> Cryo </span>are dealt <b>200/240/280/320/360%</b> ATK DMG. Can only occur once every 10s.',
    locationEn: 'Crafting',
    locationVi: 'Rèn',
  },
  {
    nameEn: 'Favonius Codex',
    nameVi: 'Tây Phong Mật Điển',
    typeEn: typeEn.Catalyst,
    typeVi: typeVi.Catalyst,
    rarity: 4,
    ATK: 42,
    secondaryVi: secondVi.ER,
    secondaryEn: secondEn.ER,
    bonusVi:
      'Khi tạo thành bạo kích có tỷ lệ <b>60/70/80/90/100%</b> sinh ra một lượng nhỏ Nguyên Tố Hạt Nhân, khôi phục 6 Năng Lượng Nguyên Tố cho nhân vật. Mỗi <b>12/10.5/9/7.5/6s</b> mới thi triển 1 lần.',
    bonusEn:
      'CRIT hits have a <b>60/70/80/90/100%</b> chance to generate 1 Elemental Orb, which will regenerate 6 Energy for the character. Can only occur once every <b>12/10.5/9/7.5/6s</b>.',
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: 'Eye of Perception',
    nameVi: 'Chiêu Tâm',
    typeEn: typeEn.Catalyst,
    typeVi: typeVi.Catalyst,
    rarity: 4,
    ATK: 0,
    secondaryVi: secondVi.ATK,
    secondaryEn: secondEn.ATK,
    bonusVi:
      'Khi tấn công thường và trọng kích đánh trúng, có 50% tỷ lệ thi triển 1 cầu phép Chiêu Tâm, gây sát thương bằng <b>240/270/300/330/360%</b> lực tấn công, tối đa bắn 4 lần vào địch. Mỗi <b>12/11/10/9/8s</b> thi triển nhiều nhất 1 lần.',
    bonusEn:
      'Normal and Charged Attacks have a 50% chance to fire a Bolt of Perception, dealing <b>240/270/300/330/360%</b> ATK as DMG. This bolt can bounce between enemies a maximum of 4 times. This effect can occur once every <b>12/11/10/9/8s</b>.',
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: 'Blackcliff Amulet',
    nameVi: 'Hắc Nham Phỉ Ngọc',
    typeEn: typeEn.Catalyst,
    typeVi: typeVi.Catalyst,
    rarity: 4,
    ATK: 42,
    secondaryVi: secondVi.CD,
    secondaryEn: secondEn.CD,
    bonusVi:
      'Sau khi đánh bại kẻ địch, tấn công tăng <b>12/15/18/21/24%</b>, kéo dài 30s. Hiệu quả này cộng dồn đến 3 tầng, CD mỗi tầng độc lập.',
    bonusEn:
      'After defeating an enemy, ATK is increased by <b>12/15/18/21/24%</b> for 30s. This effect has a maximum of 3 stacks, and the duration of each stack is independent of the others.',
    locationEn: 'Starglitter Exchange',
    locationVi: 'Đổi Tinh Huy',
  },
  {
    nameEn: 'Windblume Ode',
    nameVi: 'Bài Ca Hoa Gió',
    typeEn: typeEn.Bow,
    typeVi: typeVi.Bow,
    rarity: 4,
    ATK: 42,
    secondaryVi: secondVi.EM,
    secondaryEn: secondEn.EM,
    bonusVi:
      'Khi thi triển kỹ năng nguyên tố, nhận được lời chúc của Hoa Gió cổ xưa, tấn công tăng <b>16/20/24/28/32%</b>, kéo dài 6s.',
    bonusEn:
      'After using an Elemental Skill, receive a boon from the ancient wish of the Windblume, increasing ATK by <b>16/20/24/28/32%</b> for 6s.',
    locationEn: 'Windblume Event Reward',
    locationVi: 'Phần thưởng sự kiện Hoa Gió',
  },
  {
    nameEn: 'The Viridescent Hunt',
    nameVi: 'Cung Sắc Xanh',
    typeEn: typeEn.Bow,
    typeVi: typeVi.Bow,
    rarity: 4,
    ATK: 42,
    secondaryVi: secondVi.CR,
    secondaryEn: secondEn.CR,
    bonusVi:
      'Khi tấn công thường và trọng kích đánh trúng, có 50% tỷ lệ gây ra 1 mắt gió, thu hút địch xung quanh và mỗi 0.5s gây cho chúng sát thương bằng <b>40/50/60/70/80%</b> tấn công. Hiệu quả kéo dài 4s, mỗi <b>14/13/12/11/10s</b> thi triển nhiều nhất 1 lần.',
    bonusEn:
      'Upon hit, Normal and Aimed Shot Attacks have a 50% chance to generate a Cyclone, which will continuously attract surrounding enemies, dealing <b>40/50/60/70/80%</b> of ATK as DMG to these enemies every 0.5s for 4s. This effect can only occur once every <b>14/13/12/11/10s</b>.',
    locationEn: 'BP Bounty',
    locationVi: 'Thưởng BP',
  },
  {
    nameEn: 'The Stringless',
    nameVi: 'Tuyệt Huyền',
    typeEn: typeEn.Bow,
    typeVi: typeVi.Bow,
    rarity: 4,
    ATK: 42,
    secondaryVi: secondVi.EM,
    secondaryEn: secondEn.EM,
    bonusVi: 'Tăng <b>24/30/36/42/48%</b> sát thương kỹ năng Nguyên Tố và kỹ năng nộ.',
    bonusEn: 'Increases Elemental Skill and Elemental Burst DMG by <b>24/30/36/42/48%</b>.',
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: 'Sacrificial Bow',
    nameVi: 'Cung Tế Lễ',
    typeEn: typeEn.Bow,
    typeVi: typeVi.Bow,
    rarity: 4,
    ATK: 44,
    secondaryVi: secondVi.ER,
    secondaryEn: secondEn.ER,
    bonusVi:
      'Khi kỹ năng Nguyên Tố tạo thành sát thương, có tỷ lệ <b>40/50/60/70/80%</b> làm mới thời gian CD kỹ năng đó, mỗi <b>30/26/22/18/14s</b> mới thi triển 1 lần.',
    bonusEn:
      'After damaging an opponent with an Elemental Skill, the skill has a <b>40/50/60/70/80%</b> chance to end its own CD. Can only occur once every <b>30/26/22/18/14s</b>.',
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: 'Rust',
    nameVi: 'Cung Rỉ Sét',
    typeEn: typeEn.Bow,
    typeVi: typeVi.Bow,
    rarity: 4,
    ATK: 42,
    secondaryVi: secondVi.ATK,
    secondaryEn: secondEn.ATK,
    bonusVi:
      'Tăng <b>40/50/60/70/80%</b> sát thương của tấn công thường, giảm 10% sát thương trọng kích.',
    bonusEn:
      'Increases Normal Attack DMG by <b>40/50/60/70/80%</b> but decreases Aimed Shot DMG by 10%',
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: 'Royal Bow',
    nameVi: 'Trường Cung Tông Thất',
    typeEn: typeEn.Bow,
    typeVi: typeVi.Bow,
    rarity: 4,
    ATK: 42,
    secondaryVi: secondVi.ATK,
    secondaryEn: secondEn.ATK,
    bonusVi:
      'Khi tấn công tạo thành sát thương, tăng tỷ lệ bạo kích <b>8/10/12/14/16%</b>, nhiều nhất cộng dồn 5 lần. Sau khi tấn công tạo thành bạo kích, xóa hiệu quả Chuyên Chú đã có.',
    bonusEn:
      'Upon damaging an enemy, increases CRIT Rate by <b>8/10/12/14/16%</b>. Max 5 stacks. A CRIT hit removes all stacks.',
    locationEn: 'Starglitter Exchange',
    locationVi: 'Đổi Tinh Huy',
  },
  {
    nameEn: 'Prototype Crescent',
    nameVi: 'Mẫu Đạm Nguyệt',
    typeEn: typeEn.Bow,
    typeVi: typeVi.Bow,
    rarity: 4,
    ATK: 42,
    secondaryVi: secondVi.ATK,
    secondaryEn: secondEn.ATK,
    bonusVi:
      'Nếu trọng kích đánh trúng điểm yếu, sẽ tăng 10% tốc độ di chuyển và <b>36/45/54/63/72%</b> tấn công, kéo dài 10s.',
    bonusEn:
      'Aimed Shot hits on weak points increase Movement SPD by 10% and ATK by <b>36/45/54/63/72%</b> for 10s.',
    locationEn: 'Crafting',
    locationVi: 'Rèn',
  },
  {
    nameEn: 'Favonius Warbow',
    nameVi: 'Cung Tây Phong',
    typeEn: typeEn.Bow,
    typeVi: typeVi.Bow,
    rarity: 4,
    ATK: 41,
    secondaryVi: secondVi.ER,
    secondaryEn: secondEn.ER,
    bonusVi:
      'Khi tạo thành bạo kích có tỷ lệ <b>60/70/80/90/100%</b> sinh ra một lượng nhỏ Nguyên Tố Hạt Nhân, khôi phục 6 Năng Lượng Nguyên Tố cho nhân vật. Mỗi <b>12/10.5/9/7.5/6s</b> mới thi triển 1 lần.',
    bonusEn:
      'CRIT hits have a <b>60/70/80/90/100%</b> chance to generate 1 Elemental Orb, which will regenerate 6 Energy for the character. Can only occur once every <b>12/10.5/9/7.5/6s</b>.',
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: 'Compound Bow',
    nameVi: 'Cung Thép',
    typeEn: typeEn.Bow,
    typeVi: typeVi.Bow,
    rarity: 4,
    ATK: 41,
    secondaryVi: secondVi.PDM,
    secondaryEn: secondEn.PDM,
    bonusVi:
      'Khi đánh thường và trọng kích đánh trúng địch, tăng <b>4/5/6/7/8%</b> tấn công và <b>1.2/1.5/1.8/2.1/2.4%</b> tốc độ đánh thường. Kéo dài 6s, cộng dồn 4 tầng, mỗi 0.3s mới thi triển 1 lần.',
    bonusEn:
      'Normal Attack and Aimed Shot hits increase ATK by <b>4/5/6/7/8%</b> and Normal Attack SPD by <b>1.2/1.5/1.8/2.1/2.4%</b> for 6s. Max 4 stacks. Can only occur once every 0.3s.',
    locationEn: 'Crafting',
    locationVi: 'Rèn',
  },
  {
    nameEn: 'Blackcliff Warbow',
    nameVi: 'Cung Hắc Nham',
    typeEn: typeEn.Bow,
    typeVi: typeVi.Bow,
    rarity: 4,
    ATK: 44,
    secondaryVi: secondVi.CD,
    secondaryEn: secondEn.CD,
    bonusVi:
      'Sau khi đánh bại kẻ địch, tấn công tăng <b>12/15/18/21/24%</b>, kéo dài 30s. Hiệu quả này cộng dồn đến 3 tầng, CD mỗi tầng độc lập.',
    bonusEn:
      'After defeating an enemy, ATK is increased by <b>12/15/18/21/24%</b> for 30s. This effect has a maximum of 3 stacks, and the duration of each stack is independent of the others.',
    locationEn: 'Starglitter Exchange',
    locationVi: 'Đổi Tinh Huy',
  },
  {
    nameEn: 'Alley Hunter',
    nameVi: 'Thợ Săn Hẻm Tối',
    typeEn: typeEn.Bow,
    typeVi: typeVi.Bow,
    rarity: 4,
    ATK: 44,
    secondaryVi: secondVi.ATK,
    secondaryEn: secondEn.ATK,
    bonusVi:
      'Khi nhân vật trang bị vũ khí này ở trong đội, cứ mỗi giây nhân vật sẽ tăng <b>2/2.5/3/3.5/4%</b> sát thương tạo thành, tối đa có thể dùng cách này để tăng <b>20/25/30/35/40%</b> sát thương. Sau khi ra trận quá 4s, hiệu quả sát thương tăng thêm nêu trên sẽ mất đi 4% sau mỗi giây, cho đến khi giảm xuống còn 0%.',
    bonusEn:
      'While the character equipped with this weapon is in the party but not on the field, their DMG increases by <b>2/2.5/3/3.5/4%</b> every second up to a max of <b>20/25/30/35/40%</b>. When the character is on the field for more than 4s, the aforementioned DMG buff decreases by 4% per second until it reaches 0%.',
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: 'Mitternachts Waltz',
    nameVi: 'Điệu Van Ban Đêm',
    typeEn: typeEn.Bow,
    typeVi: typeVi.Bow,
    rarity: 4,
    ATK: 42,
    secondaryVi: secondVi.PDM,
    secondaryEn: secondEn.PDM,
    bonusVi:
      'Trong 5s sau khi tấn công thường đánh trúng địch, sát thương kỹ năng nguyên tố tạo thành tăng <b>20/25/30/35/40%</b>. Trong 5s sau khi kỹ năng nguyên tố đánh trúng địch, sát thương đánh thường tạo thành tăng <b>20/25/30/35/40%</b>.',
    bonusEn:
      'Every 4s a character is on the field, their ATK increases by <b>4/5/6/7/8%</b> and their CRIT DMG increases by <b>4/5/6/7/8%</b>. This effect has a maximum of 5 stacks and will not be reset if the character leaves the field, but will be cleared when the character takes DMG.',
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: "Traveler's Handy Sword",
    nameVi: 'Kiếm Lữ Hành',
    typeEn: typeEn.Sword,
    typeVi: typeVi.Sword,
    rarity: 3,
    ATK: 40,
    secondaryVi: secondVi.DEF,
    secondaryEn: secondEn.DEF,
    bonusVi:
      'Khi nhận được Nguyên Tố Tinh Cầu hoặc Nguyên Tố Hạt Nhân, hồi phục <b>1/1.25/1.5/1.75/2%</b> HP',
    bonusEn: 'Each Elemental Orb or Particle collected restores <b>1/1.25/1.5/1.75/2%</b> HP.',
    locationEn: 'Chest',
    locationVi: 'Rương',
  },
  {
    nameEn: 'Skyrider Sword',
    nameVi: 'Kiếm Phi Thiên',
    typeEn: typeEn.Sword,
    typeVi: typeVi.Sword,
    rarity: 3,
    ATK: 38,
    secondaryVi: secondVi.ER,
    secondaryEn: secondEn.ER,
    bonusVi:
      'Sau khi thi triển Kỹ Năng Nộ, tăng <b>12/15/18/21/24%</b> tấn công và tốc độ di chuyển, kéo dài 15s.',
    bonusEn:
      'Using an Elemental Burst grants a <b>12/15/18/21/24%</b> increase in ATK and Movement SPD for 15s.',
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: 'Harbinger of Dawn',
    nameVi: 'Thần Kiếm Lê Minh',
    typeEn: typeEn.Sword,
    typeVi: typeVi.Sword,
    rarity: 3,
    ATK: 0,
    secondaryVi: secondVi.CD,
    secondaryEn: secondEn.CD,
    bonusVi: 'Khi HP trên 90%, tỷ lệ bạo kích tăng <b>14/18/22/24/28%</b>.',
    bonusEn: 'When HP is above 90%, increases CRIT Rate by <b>14/18/22/24/28%</b>.',
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: 'Fillet Blade',
    nameVi: 'Đao Săn Cá',
    typeEn: typeEn.Sword,
    typeVi: typeVi.Sword,
    rarity: 3,
    ATK: 39,
    secondaryVi: secondVi.ATK,
    secondaryEn: secondEn.ATK,
    bonusVi:
      'Khi đánh trúng, có 50% cơ hội tạo thành <b>240/280/320/360/400%</b> sát thương tấn công vào mục tiêu đơn. Hiệu quả này <b>15/14/13/12/11s</b> xuất hiện một lần.',
    bonusEn:
      'On hit, has 50% chance to deal <b>240/280/320/360/400%</b> ATK DMG to a single enemy. Can only occur once every <b>15/14/13/12/11s</b>.',
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: 'Dark Iron Sword',
    nameVi: 'Kiếm Sắt Đen',
    typeEn: typeEn.Sword,
    typeVi: typeVi.Sword,
    rarity: 3,
    ATK: 0,
    secondaryVi: secondVi.EM,
    secondaryEn: secondEn.EM,
    bonusVi:
      'Sau khi kích hoạt phản ứng quá tải, siêu dẫn, điện cảm hoặc khuếch tán Nguyên Tố Lôi, tăng <b>20/25/30/35/40%</b> tấn công trong 12s.',
    bonusEn:
      'Upon causing an Overloaded, Superconduct, Electro-Charged, or an Electro-infused Swirl reaction, increases Base ATK by <b>20/25/30/35/40%</b> for 12s.',
    locationEn: '---',
    locationVi: '---',
  },
  {
    nameEn: 'Cool Steel',
    nameVi: 'Lãnh Nhẫn',
    typeEn: typeEn.Sword,
    typeVi: typeVi.Sword,
    rarity: 3,
    ATK: 39,
    secondaryVi: secondVi.ATK,
    secondaryEn: secondEn.ATK,
    bonusVi:
      'Sát thương tạo ra cho kẻ địch bị ảnh hưởng bởi nguyên tố<span class="hydro"> Thủy </span>hoặc<span class="cryo"> Băng </span>tăng <b>12/15/18/21/24%</b>.',
    bonusEn:
      'Increases DMG against enemies affected by<span class="hydro"> Hydro </span>or<span class="cryo"> Cryo </span>by <b>12/15/18/21/24%</b>.',
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: 'White Tassel',
    nameVi: 'Thương Bạch Anh',
    typeEn: typeEn.Polearm,
    typeVi: typeVi.Polearm,
    rarity: 3,
    ATK: 39,
    secondaryVi: secondVi.CR,
    secondaryEn: secondEn.CR,
    bonusVi: 'Tấn công thường sát thương tăng <b>24/30/36/42/48%</b>.',
    bonusEn: 'Increases Normal Attack DMG by <b>24/30/36/42/48%</b>.',
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: 'Halberd',
    nameVi: 'Thuẫn Kích',
    typeEn: typeEn.Polearm,
    typeVi: typeVi.Polearm,
    rarity: 3,
    ATK: 40,
    secondaryVi: secondVi.ATK,
    secondaryEn: secondEn.ATK,
    bonusVi:
      'Tạo thành thêm <b>160/200/240/280/320%</b> công kích cho kẻ địch bị tấn công thường đánh trúng. Mỗi 10s mới thi triển 1 lần.',
    bonusEn:
      'Normal Attacks deal an additional <b>160/200/240/280/320%</b> DMG. Can only occur once every 10s.',
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: 'Black Tassel',
    nameVi: 'Hắc Anh Thương',
    typeEn: typeEn.Polearm,
    typeVi: typeVi.Polearm,
    rarity: 3,
    ATK: 38,
    secondaryVi: secondVi.HP,
    secondaryEn: secondEn.HP,
    bonusVi: 'Tăng <b>40/50/60/70/80%</b> sát thương với kẻ địch là Slime.',
    bonusEn: 'Increases DMG against slimes by <b>40/50/60/70/80%</b>.',
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: 'White Iron Greatsword',
    nameVi: 'Kiếm Bạch Thiết',
    typeEn: typeEn.Claymore,
    typeVi: typeVi.Claymore,
    rarity: 3,
    ATK: 39,
    secondaryVi: secondVi.DEF,
    secondaryEn: secondEn.DEF,
    bonusVi: 'Khi đánh bại kẻ địch, hồi <b>8/10/12/14/16%</b> HP.',
    bonusEn: 'Defeating an opponent restores <b>8/10/12/14/16%</b> HP.',
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: 'Skyrider Greatsword',
    nameVi: 'Đại Kiếm Phi Thiên',
    typeEn: typeEn.Claymore,
    typeVi: typeVi.Claymore,
    rarity: 3,
    ATK: 39,
    secondaryVi: secondVi.PDM,
    secondaryEn: secondEn.PDM,
    bonusVi:
      'Khi tấn công thường và trọng kích đánh trúng địch, tấn công tăng <b>6/7/8/9/10%</b>, kéo dài 6s, tối đa cộng dồn 4 lần. Mỗi 0.5s mới thi triển 1 lần.',
    bonusEn:
      'On hit, Normal or Charged Attacks increase ATK by <b>6/7/8/9/10%</b> for 6s. Max 4 stacks. Can only occur once every 0.5s.',
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: 'Quartz',
    nameVi: 'Kiếm Thạch Anh',
    typeEn: typeEn.Claymore,
    typeVi: typeVi.Claymore,
    rarity: 3,
    ATK: 39,
    secondaryVi: secondVi.EM,
    secondaryEn: secondEn.EM,
    bonusVi:
      'Sau khi kích hoạt phản ứng Quá Tải, Tan Chảy, Đốt Cháy, Bốc Hơi hoặc Khuếch Tán Nguyên Tố Hỏa, trong 12s tăng tấn công <b>20/25/30/35/40%</b>',
    bonusEn:
      'Upon causing an Overloaded, Melt, Burning, Vaporize, or a Pyro-infused Swirl reaction, increases Base ATK by <b>20/25/30/35/40%</b> for 12s.',
    locationEn: '--',
    locationVi: '--',
  },
  {
    nameEn: 'Ferrous Shadow',
    nameVi: 'Kiếm Thiết Ảnh',
    typeEn: typeEn.Claymore,
    typeVi: typeVi.Claymore,
    rarity: 3,
    ATK: 39,
    secondaryVi: secondVi.HP,
    secondaryEn: secondEn.HP,
    bonusVi:
      'Khi HP dưới <b>70/75/80/85/90%</b>, trọng kích khó bị ngắt đoạn, và tăng <b>30/35/40/45/50%</b> sát thương trọng kích.',
    bonusEn:
      'When HP falls below <b>70/75/80/85/90%</b>, increases Charged Attack DMG by <b>30/35/40/45/50%</b>, and Charged Attacks become much harder to interrupt.',
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: 'Debate Club',
    nameVi: 'Gậy Thu Phục',
    typeEn: typeEn.Claymore,
    typeVi: typeVi.Claymore,
    rarity: 3,
    ATK: 39,
    secondaryVi: secondVi.ATK,
    secondaryEn: secondEn.ATK,
    bonusVi:
      'Sau khi thi triển kỹ năng nguyên tố, tấn công thường và trọng kích đánh trúng địch sẽ tạo thêm sát thương bằng <b>60/75/90/105/120%</b>  tấn công trong phạm vi nhỏ. Hiệu quả kéo dài 15s, sát thương mỗi 3s mới thi triển 1 lần.',
    bonusEn:
      'After using an Elemental Skill, Normal or Charged Attacks, on hit, deal an additional <b>60/75/90/105/120%</b> ATK DMG in a small area. Effect lasts 15s. DMG can only occur once every 3s.',
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: 'Bloodtainted Greatsword',
    nameVi: 'Kiếm Huyết Rồng',
    typeEn: typeEn.Claymore,
    typeVi: typeVi.Claymore,
    rarity: 3,
    ATK: 38,
    secondaryVi: secondVi.EM,
    secondaryEn: secondEn.EM,
    bonusVi:
      'Sát thương tạo ra cho kẻ địch bị ảnh hưởng bởi nguyên tố<span class="pyro"> Hỏa </span>hoặc<span class="electro"> Lôi </span>tăng 12%.',
    bonusEn:
      'Increases DMG against enemies affected by<span class="pyro"> Pyro </span>or<span class="electro"> Electro </span>by <b>12/15/18/21/24%</b>.',
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: 'Twin Nephrite',
    nameVi: 'Ngọc Sinh Đôi',
    typeEn: typeEn.Catalyst,
    typeVi: typeVi.Catalyst,
    rarity: 3,
    ATK: 40,
    secondaryVi: secondVi.CR,
    secondaryEn: secondEn.CR,
    bonusVi:
      'Trong 15s sau khi đánh bại kẻ địch, tốc độ di chuyển và tấn công tăng <b>12/14/16/18/20%</b>.',
    bonusEn: 'Defeating an enemy increases Movement SPD and ATK by <b>12/14/16/18/20%</b> for 15s.',
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: 'Thrilling Tales of Dragon Slayers',
    nameVi: 'Câu Chuyện Diệt Rồng',
    typeEn: typeEn.Catalyst,
    typeVi: typeVi.Catalyst,
    rarity: 3,
    ATK: 39,
    secondaryVi: secondVi.HP,
    secondaryEn: secondEn.HP,
    bonusVi:
      'Khi chủ động đổi nhân vật, tấn công của nhân vật mới vào trận tăng <b>24/30/36/42/48%</b>, kéo dài 10s. Mỗi 20s mới thi triển 1 lần.',
    bonusEn:
      'When switching characters, the new character taking the field has their ATK increased by <b>24/30/36/42/48%</b> for 10s. This effect can only occur once every 20s.',
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: 'Otherworldly Story',
    nameVi: 'Tiểu Thuyết Dị Giới',
    typeEn: typeEn.Catalyst,
    typeVi: typeVi.Catalyst,
    rarity: 3,
    ATK: 39,
    secondaryVi: secondVi.ER,
    secondaryEn: secondEn.ER,
    bonusVi:
      'Khi nhận được Nguyên Tố Tinh Cầu hoặc Nguyên Tố Hạt Nhân, hồi phục <b>1/1.25/1.5/1.75/2%</b> HP',
    bonusEn: 'Each Elemental Orb or Particle collected restores <b>1/1.25/1.5/1.75/2%</b> HP.',
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: 'Magic Guide',
    nameVi: 'Tóm Tắt Ma Pháp',
    typeEn: typeEn.Catalyst,
    typeVi: typeVi.Catalyst,
    rarity: 3,
    ATK: 38,
    secondaryVi: secondVi.EM,
    secondaryEn: secondEn.EM,
    bonusVi:
      'Sát thương tạo ra cho kẻ địch bị ảnh hưởng bởi nguyên tố<span class="hydro"> Thủy </span>hoặc<span class="electro"> Lôi </span>tăng <b>12/15/18/21/24%</b>.',
    bonusEn:
      'Increases DMG against enemies affected by<span class="hydro"> Hydro </span>or<span class="electro"> Electro </span>by <b>12/15/18/21/24%</b>.',
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: 'Emerald Orb',
    nameVi: 'Quả Cầu Ngọc',
    typeEn: typeEn.Catalyst,
    typeVi: typeVi.Catalyst,
    rarity: 3,
    ATK: 40,
    secondaryVi: secondVi.EM,
    secondaryEn: secondEn.EM,
    bonusVi:
      'Sau khi kích hoạt phản ứng bốc hơi, điện cảm, đóng băng hoặc khuếch tán Nguyên Tố Thủy, trong 12s tăng tấn công <b>20/25/30/35/40%</b>.',
    bonusEn:
      'Upon causing a Vaporize, Electro-Charged, Frozen, or a Hydro-infused Swirl reaction, increases Base ATK by <b>20/25/30/35/40%</b> for 12s.',
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: 'Amber Catalyst',
    nameVi: 'Hổ Phách Nguyệt',
    typeEn: typeEn.Catalyst,
    typeVi: typeVi.Catalyst,
    rarity: 3,
    ATK: 39,
    secondaryVi: secondVi.EM,
    secondaryEn: secondEn.EM,
    bonusVi:
      'Sau khi tấn công thường đánh trúng địch, nhận <b>6/7.5/9/10.5/12%</b> buff sát thương Nguyên Tố. Hiệu quả kéo dài 6s, cộng dồn 2 tầng.',
    bonusEn:
      'Normal Attack hits increase all Elemental DMG by <b>6/7.5/9/10.5/12%</b> for 6s. Max 2 stacks.',
    locationEn: '--',
    locationVi: '--',
  },
  {
    nameEn: 'Slingshot',
    nameVi: 'Nỏ Kéo',
    typeEn: typeEn.Bow,
    typeVi: typeVi.Bow,
    rarity: 3,
    ATK: 38,
    secondaryVi: secondVi.CR,
    secondaryEn: secondEn.CR,
    bonusVi:
      'Khi đánh thường hoặc trọng kích, nếu mũi tên bắn trúng kẻ địch trong 0.3s sau khi phóng, sát thương tạo thành sẽ tăng <b>36/42/48/54/60%</b>. Nếu không, sát thương tạo thành giảm 10%.',
    bonusEn:
      'If a Normal Attack or Aimed Shot hits a target within 0.3s of being fired, increases DMG by <b>36/42/48/54/60%</b>. Otherwise, it decreases DMG by 10%.',
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: "Sharpshooter's Oath",
    nameVi: 'Lời Thề Xạ Thủ Thần',
    typeEn: typeEn.Bow,
    typeVi: typeVi.Bow,
    rarity: 3,
    ATK: 39,
    secondaryVi: secondVi.CR,
    secondaryEn: secondEn.CR,
    bonusVi: 'Tăng <b>24/30/36/42/48%</b> sát thương tạo thành với điểm yếu.',
    bonusEn: 'Increases DMG against weak spots by <b>24/30/36/42/48%</b>.',
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: 'Recurve Bow',
    nameVi: 'Cung Phản Khúc',
    typeEn: typeEn.Bow,
    typeVi: typeVi.Bow,
    rarity: 3,
    ATK: 38,
    secondaryVi: secondVi.HP,
    secondaryEn: secondEn.HP,
    bonusVi: 'Khi đánh bại kẻ địch, hồi <b>8/10/12/14/16%</b> HP.',
    bonusEn: 'Defeating an opponent restores <b>8/10/12/14/16%</b> HP.',
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: 'Raven Bow',
    nameVi: 'Cung Lông Vịt',
    typeEn: typeEn.Bow,
    typeVi: typeVi.Bow,
    rarity: 3,
    ATK: 40,
    secondaryVi: secondVi.EM,
    secondaryEn: secondEn.EM,
    bonusVi:
      'Sát thương tạo ra cho kẻ địch bị ảnh hưởng bởi nguyên tố<span class="hydro"> Thủy </span>hoặc<span class="pyro"> Hỏa </span>tăng <b>12/15/18/21/24%</b>.',
    bonusEn:
      'Increases DMG against enemies affected by<span class="hydro"> Hydro </span>or<span class="pyro"> Pyro </span>by <b>12/15/18/21/24%</b>.',
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: 'Messenger',
    nameVi: 'Tín Sứ',
    typeEn: typeEn.Bow,
    typeVi: typeVi.Bow,
    rarity: 3,
    ATK: 40,
    secondaryVi: secondVi.CD,
    secondaryEn: secondEn.CD,
    bonusVi:
      'Nếu trọng kích đánh trúng điểm yếu, sẽ tạo thành thêm sát thương bằng <b>100/125/150/175/200%</b> tấn công, sát thương này chắc chắn bạo kích. Mỗi 10s chỉ có hiệu quả 1 lần.',
    bonusEn:
      'Aimed Shot hits on weak spots deal an additional <b>100/125/150/175/200%</b> ATK DMG as CRIT DMG. Can only occur once every 10s.',
    locationEn: 'Gacha',
    locationVi: 'Gacha',
  },
  {
    nameEn: 'Ebony Bow',
    nameVi: 'Cung Hắc Đàn',
    typeEn: typeEn.Bow,
    typeVi: typeVi.Bow,
    rarity: 3,
    ATK: 39,
    secondaryVi: secondVi.ATK,
    secondaryEn: secondEn.ATK,
    bonusVi: 'Sát thương gây ra tăng <b>40/50/60/70/80%</b> đối với kẻ địch thuộc cơ quan di tích.',
    bonusEn: 'Increases DMG against mechanoid Ruin enemies by <b>40/50/60/70/80%</b>.',
    locationEn: '--',
    locationVi: '--',
  },
  {
    nameEn: 'Silver Sword',
    nameVi: 'Kiếm Bạc',
    typeEn: typeEn.Sword,
    typeVi: typeVi.Sword,
    rarity: 2,
    ATK: 33,
    secondaryVi: '..',
    secondaryEn: '..',
    bonusVi: '..',
    bonusEn: '..',
    locationEn: 'Chest',
    locationVi: 'Rương',
  },
  {
    nameEn: 'Iron Point',
    nameVi: 'Thương Sắt',
    typeEn: typeEn.Polearm,
    typeVi: typeVi.Polearm,
    rarity: 2,
    ATK: 33,
    secondaryVi: '..',
    secondaryEn: '..',
    bonusVi: '..',
    bonusEn: '..',
    locationEn: 'Chest',
    locationVi: 'Rương',
  },
  {
    nameEn: 'Old Merc\'s Pal',
    nameVi: 'Kiếm Dụng Binh',
    typeEn: typeEn.Claymore,
    typeVi: typeVi.Claymore,
    rarity: 2,
    ATK: 33,
    secondaryVi: '..',
    secondaryEn: '..',
    bonusVi: '..',
    bonusEn: '..',
    locationEn: 'Chest',
    locationVi: 'Rương',
  },
  {
    nameEn: 'Pocket Grimoire',
    nameVi: 'Sổ Tay Ma Pháp',
    typeEn: typeEn.Catalyst,
    typeVi: typeVi.Catalyst,
    rarity: 2,
    ATK: 33,
    secondaryVi: '..',
    secondaryEn: '..',
    bonusVi: '..',
    bonusEn: '..',
    locationEn: 'Chest',
    locationVi: 'Rương',
  },
  {
    nameEn: 'Seasoned Hunter\'s Bow',
    nameVi: 'Cung Săn Bắn Tôi Luyện',
    typeEn: typeEn.Bow,
    typeVi: typeVi.Bow,
    rarity: 2,
    ATK: 33,
    secondaryVi: '..',
    secondaryEn: '..',
    bonusVi: '..',
    bonusEn: '..',
    locationEn: 'Chest',
    locationVi: 'Rương',
  },
  {
    nameEn: 'Dull Blade',
    nameVi: 'Vô Phong Kiếm',
    typeEn: typeEn.Sword,
    typeVi: typeVi.Sword,
    rarity: 1,
    ATK: 23,
    secondaryVi: '..',
    secondaryEn: '..',
    bonusVi: '..',
    bonusEn: '..',
    locationEn: 'Chest',
    locationVi: 'Rương',
  },
  {
    nameEn: 'Beginner\'s Protector',
    nameVi: 'Thương Tân Thủ',
    typeEn: typeEn.Polearm,
    typeVi: typeVi.Polearm,
    rarity: 1,
    ATK: 23,
    secondaryVi: '..',
    secondaryEn: '..',
    bonusVi: '..',
    bonusEn: '..',
    locationEn: 'Chest',
    locationVi: 'Rương',
  },
  {
    nameEn: 'Waster Greatsword',
    nameVi: 'Kiếm Dụng Binh',
    typeEn: typeEn.Claymore,
    typeVi: typeVi.Claymore,
    rarity: 1,
    ATK: 23,
    secondaryVi: '..',
    secondaryEn: '..',
    bonusVi: '..',
    bonusEn: '..',
    locationEn: 'Chest',
    locationVi: 'Rương',
  },
  {
    nameEn: 'Apprentice\'s Notes',
    nameVi: 'Nhật Ký Học Sinh',
    typeEn: typeEn.Catalyst,
    typeVi: typeVi.Catalyst,
    rarity: 1,
    ATK: 23,
    secondaryVi: '..',
    secondaryEn: '..',
    bonusVi: '..',
    bonusEn: '..',
    locationEn: 'Chest',
    locationVi: 'Rương',
  },
  {
    nameEn: 'Hunter\'s Bow',
    nameVi: 'Cung Săn Bắn',
    typeEn: typeEn.Bow,
    typeVi: typeVi.Bow,
    rarity: 1,
    ATK: 23,
    secondaryVi: '..',
    secondaryEn: '..',
    bonusVi: '..',
    bonusEn: '..',
    locationEn: 'Chest',
    locationVi: 'Rương',
  },
]
export { BaseWeapon, WeaponList }
